/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index" |
       "/pages/A-top" |
       "/pages/i18n" |
       "/pages/test-json" |
       "/pages/test-jsonc-with-comment" |
       "/pages/test-yaml" |
       "/pages/test" |
       "/pages/blog/index" |
       "/pages/blog/post" |
       "/pages-sub/index" |
       "/pages-sub/about/index" |
       "/pages-sub/about/your";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
