import { describe, expect, it } from 'vitest'
import { mergePagesJson } from '../packages/core/src'

/**
 * Regression coverage: home page status must survive multi-platform merging.
 *
 * Reporter scenario: `dev:mp-weixin` and `dev:web` run at the same time
 * against one shared pages.json.
 *
 * Symptom 1 — marking another page as home (`definePage({ type: 'home' })`
 * in pages/test.vue) moved the page first but kept stale `type` markers:
 * test stayed `"type": "page"` and index kept `"type": "home"`.
 *
 * Symptom 2 — platform-scoped home via `define().ifdef('mp-weixin',
 * { type: 'home' })` produced no per-platform entries at all; whichever
 * platform wrote first won and the other platform's home was silently lost.
 *
 * Both trace back to the merge equality check normalizing the internal
 * `type` marker away, so home-status changes compared "equal" to the stale
 * persisted entry and the stale object survived.
 */

/** Parse the generated pages.json text into plain entries plus their #ifdef platform block (if any) */
function parseEntries(content: string): Array<{ path: string, type?: string, ifdef?: string }> {
  const lines = content.split('\n')
  const entries: Array<{ path: string, type?: string, ifdef?: string }> = []
  let currentIfdef: string | undefined
  let current: { path: string, type?: string, ifdef?: string } | undefined

  for (const line of lines) {
    const trimmed = line.trim()
    const ifdefMatch = trimmed.match(/^\/\/\s*#ifdef\s+(\S.*)$/)
    if (ifdefMatch) {
      currentIfdef = ifdefMatch[1].trim()
      continue
    }
    if (trimmed === '// #endif') {
      currentIfdef = undefined
      continue
    }
    const pathMatch = trimmed.match(/"path":\s*"([^"]+)"/)
    if (pathMatch) {
      current = { path: pathMatch[1], ifdef: currentIfdef }
      entries.push(current)
      continue
    }
    const typeMatch = trimmed.match(/"type":\s*"([^"]+)"/)
    if (typeMatch && current)
      current.type = typeMatch[1]
  }
  return entries
}

/**
 * Entries a build for `platform` would see after uni-app conditional
 * compilation: unwrapped entries stay visible to every platform, wrapped
 * ones only on the platforms listed in their #ifdef block. This is exactly
 * the invariant the merge must preserve — an unwrapped entry narrower than
 * the full platform set would leak into the other platforms' views.
 */
function entriesForPlatform(content: string, platform: string): Array<{ path: string, type?: string }> {
  return parseEntries(content)
    .filter(e => !e.ifdef || e.ifdef.split('||').map(p => p.trim()).includes(platform))
    .map(({ path, type }) => ({ path, type }))
}

/** Duplicate paths in one platform view break the uni-app build */
function expectNoDuplicatePaths(view: Array<{ path: string }>): void {
  const paths = view.map(e => e.path)
  expect(new Set(paths).size).toBe(paths.length)
}

describe('home page status across concurrent platform runs', () => {
  // Converged state before the edit: index is home (resolved by the homePage
  // fallback on earlier runs), test is a plain page. Every scanned entry
  // carries the internal type marker (macro evaluation defaults to 'page').
  const converged = [
    '{',
    '  "pages": [',
    '    // GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN',
    '    {',
    '      "path": "pages/index",',
    '      "type": "home",',
    '      "middlewares": [',
    '        "auth",',
    '        "test"',
    '      ]',
    '    },',
    '    {',
    '      "path": "pages/test",',
    '      "type": "page",',
    '      "style": {',
    '        "navigationBarTitleText": "test page"',
    '      },',
    '      "middlewares": [',
    '        "auth"',
    '      ]',
    '    }',
    '  ],',
    '  "subPackages": []',
    '}',
    '',
  ].join('\n')

  it('propagates a home switch once both platforms have re-run (symptom 1)', () => {
    // The user adds `type: 'home'` to pages/test.vue; both dev servers watch
    // the file and re-scan. mp-weixin merges first against the stale file...
    const afterWeixin = mergePagesJson(converged, {
      pages: [
        { path: 'pages/test', type: 'home', style: { navigationBarTitleText: 'test page' }, middlewares: ['auth'] },
        { path: 'pages/index', type: 'page', middlewares: ['auth', 'test'] },
      ],
      subPackages: [],
      homePath: 'pages/test',
    }, { platform: 'mp-weixin' })

    // Intermediate state: until h5 re-runs, the stale shared entries
    // survive as wrapped per-platform variants. Both platform views must
    // already be leak-free (no duplicate path) with their own home first.
    const midWeixinView = entriesForPlatform(afterWeixin, 'MP-WEIXIN')
    const midH5View = entriesForPlatform(afterWeixin, 'H5')
    expectNoDuplicatePaths(midWeixinView)
    expectNoDuplicatePaths(midH5View)
    expect(midWeixinView[0]).toEqual({ path: 'pages/test', type: 'home' })
    expect(midH5View[0]).toEqual({ path: 'pages/index', type: 'home' })

    // ...then h5 merges the same fresh scan over that intermediate state.
    const final = mergePagesJson(afterWeixin, {
      pages: [
        { path: 'pages/test', type: 'home', style: { navigationBarTitleText: 'test page' }, middlewares: ['auth'] },
        { path: 'pages/index', type: 'page', middlewares: ['auth', 'test'] },
      ],
      subPackages: [],
      homePath: 'pages/test',
    }, { platform: 'h5' })

    const entries = parseEntries(final)
    expect(entries).toHaveLength(2)

    // The stale markers must not survive: test is home, index is a plain page
    const test = entries.find(e => e.path === 'pages/test')!
    const index = entries.find(e => e.path === 'pages/index')!
    expect(test.type).toBe('home')
    expect(index.type).toBe('page')

    // Home stays first on every platform view, without leaking duplicates
    expect(final.indexOf('"pages/test"')).toBeLessThan(final.indexOf('"pages/index"'))
    const finalH5View = entriesForPlatform(final, 'H5')
    const finalWeixinView = entriesForPlatform(final, 'MP-WEIXIN')
    expectNoDuplicatePaths(finalH5View)
    expectNoDuplicatePaths(finalWeixinView)
    expect(finalH5View[0].path).toBe('pages/test')
    expect(finalWeixinView[0].path).toBe('pages/test')
  })

  it('keeps platform-scoped home behind #ifdef blocks (symptom 2)', () => {
    // pages/test.vue: define().ifdef('mp-weixin', { type: 'home' })
    // pages/index.vue: define().ifndef('mp-weixin', { type: 'home' })
    // h5 starts first and writes its view: index is home there.
    const afterH5 = mergePagesJson('', {
      pages: [
        { path: 'pages/index', type: 'home', middlewares: ['auth', 'test'] },
        { path: 'pages/test', type: 'page', style: { navigationBarTitleText: 'test page' }, middlewares: ['auth'] },
      ],
      subPackages: [],
      homePath: 'pages/index',
    }, { platform: 'h5' })

    // mp-weixin merges its view where test is home instead.
    const final = mergePagesJson(afterH5, {
      pages: [
        { path: 'pages/test', type: 'home', style: { navigationBarTitleText: 'test page' }, middlewares: ['auth'] },
        { path: 'pages/index', type: 'page', middlewares: ['auth', 'test'] },
      ],
      subPackages: [],
      homePath: 'pages/test',
    }, { platform: 'mp-weixin' })

    const entries = parseEntries(final)

    // Each page keeps one variant per platform instead of collapsing into
    // whichever run wrote first
    expect(entries.filter(e => e.path === 'pages/index')).toHaveLength(2)
    expect(entries.filter(e => e.path === 'pages/test')).toHaveLength(2)

    // No variant covers the full platform union, so nothing may be emitted
    // unwrapped: a bare single-platform variant would leak into the other
    // platform's view as a duplicate path
    expect(entries.filter(e => !e.ifdef)).toHaveLength(0)

    // Per-platform views: mp-weixin enters through test, h5 through index,
    // and neither view carries a duplicate path
    const weixinView = entriesForPlatform(final, 'MP-WEIXIN')
    const h5View = entriesForPlatform(final, 'H5')
    expectNoDuplicatePaths(weixinView)
    expectNoDuplicatePaths(h5View)
    expect(weixinView[0]).toEqual({ path: 'pages/test', type: 'home' })
    expect(weixinView.find(e => e.path === 'pages/index')!.type).toBe('page')
    expect(h5View[0]).toEqual({ path: 'pages/index', type: 'home' })
    expect(h5View.find(e => e.path === 'pages/test')!.type).toBe('page')

    // The result is stable: another mp-weixin run against it changes nothing
    const rerun = mergePagesJson(final, {
      pages: [
        { path: 'pages/test', type: 'home', style: { navigationBarTitleText: 'test page' }, middlewares: ['auth'] },
        { path: 'pages/index', type: 'page', middlewares: ['auth', 'test'] },
      ],
      subPackages: [],
      homePath: 'pages/test',
    }, { platform: 'mp-weixin' })
    expect(rerun).toBe(final)
  })

  it('keeps platform-scoped home stable regardless of which platform writes first', () => {
    // Mirror of the previous case with the write order reversed: exercises
    // the comment reattachment path where the displaced first entry keeps
    // its #ifdef block while the moved home variant lands at index 0.
    const afterWeixin = mergePagesJson('', {
      pages: [
        { path: 'pages/test', type: 'home', style: { navigationBarTitleText: 'test page' }, middlewares: ['auth'] },
        { path: 'pages/index', type: 'page', middlewares: ['auth', 'test'] },
      ],
      subPackages: [],
      homePath: 'pages/test',
    }, { platform: 'mp-weixin' })

    const final = mergePagesJson(afterWeixin, {
      pages: [
        { path: 'pages/index', type: 'home', middlewares: ['auth', 'test'] },
        { path: 'pages/test', type: 'page', style: { navigationBarTitleText: 'test page' }, middlewares: ['auth'] },
      ],
      subPackages: [],
      homePath: 'pages/index',
    }, { platform: 'h5' })

    const weixinView = entriesForPlatform(final, 'MP-WEIXIN')
    const h5View = entriesForPlatform(final, 'H5')
    expectNoDuplicatePaths(weixinView)
    expectNoDuplicatePaths(h5View)
    expect(weixinView[0]).toEqual({ path: 'pages/test', type: 'home' })
    expect(weixinView.find(e => e.path === 'pages/index')!.type).toBe('page')
    expect(h5View[0]).toEqual({ path: 'pages/index', type: 'home' })
    expect(h5View.find(e => e.path === 'pages/test')!.type).toBe('page')

    // Stable under a further h5 run
    const rerun = mergePagesJson(final, {
      pages: [
        { path: 'pages/index', type: 'home', middlewares: ['auth', 'test'] },
        { path: 'pages/test', type: 'page', style: { navigationBarTitleText: 'test page' }, middlewares: ['auth'] },
      ],
      subPackages: [],
      homePath: 'pages/index',
    }, { platform: 'h5' })
    expect(rerun).toBe(final)
  })

  it('keeps every platform home first once a third platform joins', () => {
    // Same DSL setup as symptom 2, now with a third platform that agrees
    // with h5: mp-alipay starts after h5 and mp-weixin have converged and
    // writes twice. The alipay run must not strand the MP-WEIXIN home
    // behind a MP-WEIXIN-visible non-home entry just because alipay's own
    // home already sits at index 0.
    const alipayPages = {
      pages: [
        { path: 'pages/index', type: 'home' as const, middlewares: ['auth', 'test'] },
        { path: 'pages/test', type: 'page' as const, style: { navigationBarTitleText: 'test page' }, middlewares: ['auth'] },
      ],
      subPackages: [],
      homePath: 'pages/index',
    }
    const afterH5 = mergePagesJson('', alipayPages, { platform: 'h5' })
    const afterWeixin = mergePagesJson(afterH5, {
      pages: [
        { path: 'pages/test', type: 'home', style: { navigationBarTitleText: 'test page' }, middlewares: ['auth'] },
        { path: 'pages/index', type: 'page', middlewares: ['auth', 'test'] },
      ],
      subPackages: [],
      homePath: 'pages/test',
    }, { platform: 'mp-weixin' })

    const afterAlipay = mergePagesJson(afterWeixin, alipayPages, { platform: 'mp-alipay' })

    // The third platform must join the generation marker's union
    expect(afterAlipay).toContain('PLATFORM: H5 || MP-ALIPAY || MP-WEIXIN')

    const weixinView = entriesForPlatform(afterAlipay, 'MP-WEIXIN')
    const h5View = entriesForPlatform(afterAlipay, 'H5')
    const alipayView = entriesForPlatform(afterAlipay, 'MP-ALIPAY')
    expectNoDuplicatePaths(weixinView)
    expectNoDuplicatePaths(h5View)
    expectNoDuplicatePaths(alipayView)

    // MP-WEIXIN must still enter through pages/test even though the alipay
    // run placed its own home (pages/index) at index 0
    expect(weixinView[0]).toEqual({ path: 'pages/test', type: 'home' })
    expect(weixinView.find(e => e.path === 'pages/index')!.type).toBe('page')
    expect(h5View[0]).toEqual({ path: 'pages/index', type: 'home' })
    expect(alipayView[0]).toEqual({ path: 'pages/index', type: 'home' })
    expect(alipayView.find(e => e.path === 'pages/test')!.type).toBe('page')

    // Stable under a further alipay run
    const rerun = mergePagesJson(afterAlipay, alipayPages, { platform: 'mp-alipay' })
    expect(rerun).toBe(afterAlipay)

    // ...and under a further weixin run: idempotence must not be specific to
    // the platform that wrote last
    const rerunWeixin = mergePagesJson(afterAlipay, {
      pages: [
        { path: 'pages/test', type: 'home', style: { navigationBarTitleText: 'test page' }, middlewares: ['auth'] },
        { path: 'pages/index', type: 'page', middlewares: ['auth', 'test'] },
      ],
      subPackages: [],
      homePath: 'pages/test',
    }, { platform: 'mp-weixin' })
    expect(rerunWeixin).toBe(afterAlipay)

    // ...and under a further h5 run: a partition that short-circuits whenever
    // the current platform's home already sits at index 0 would regress here,
    // because h5's home is at 0 while the merge emission order is not
    const rerunH5 = mergePagesJson(afterAlipay, alipayPages, { platform: 'h5' })
    expect(rerunH5).toBe(afterAlipay)
  })

  it('marks every unmarked variant of the home path on legacy files', () => {
    // Hand-written pages.json without the generation marker and without the
    // internal type markers: every scanned entry merges content-equal into a
    // legacy variant and loses its marker, so the homePath fallback kicks
    // in. It must mark every variant of the home path, not just the first:
    // the first variant may belong to another platform, and leaving the
    // current platform's own variant unmarked strands it behind visible
    // non-home entries until a later self-healing write.
    const legacy = [
      '{',
      '  "pages": [',
      '    // #ifdef APP',
      '    {',
      '      "path": "pages/a"',
      '    },',
      '    // #endif',
      '    // #ifdef H5',
      '    {',
      '      "path": "pages/index",',
      '      "style": {',
      '        "navigationBarTitleText": "h5"',
      '      }',
      '    },',
      '    // #endif',
      '    // #ifdef MP-WEIXIN || APP',
      '    {',
      '      "path": "pages/index",',
      '      "style": {',
      '        "navigationBarTitleText": "wx"',
      '      }',
      '    }',
      '    // #endif',
      '  ]',
      '}',
    ].join('\n')

    const scan = {
      pages: [
        { path: 'pages/a', type: 'page' as const },
        { path: 'pages/index', type: 'home' as const, style: { navigationBarTitleText: 'wx' } },
      ],
      subPackages: [],
      homePath: 'pages/index',
    }
    const merged = mergePagesJson(legacy, scan, { platform: 'mp-weixin' })

    // MP-WEIXIN enters through pages/index even though the first homePath
    // variant in the file is H5-only and a visible non-home entry precedes
    // the weixin variant in the source
    const weixinView = entriesForPlatform(merged, 'MP-WEIXIN')
    expectNoDuplicatePaths(weixinView)
    expect(weixinView[0]?.path).toBe('pages/index')
    expect(entriesForPlatform(merged, 'H5')[0]?.path).toBe('pages/index')

    // The stable partition keeps the home variants in source order ahead of
    // the non-home entry: [index(H5), index(APP || MP-WEIXIN), a]
    expect(parseEntries(merged).map(e => e.path)).toEqual(['pages/index', 'pages/index', 'pages/a'])

    // Byte-stable under a further weixin run: the fallback re-derives home
    // status from homePath every run, and the partition short-circuit keeps
    // the already-partitioned output untouched
    expect(mergePagesJson(merged, scan, { platform: 'mp-weixin' })).toBe(merged)
  })
})
