import type { CommentObject } from 'comment-json'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parse as cjParse } from 'comment-json'
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { PageContext } from '../packages/core/src'

/**
 * Regression coverage for stale sub-package convergence in writePagesJson.
 *
 * Before this change, a sub-package missing from the current run's scan
 * (every page opted out via definePage(null), or the directory removed)
 * stayed frozen in pages.json forever: the merge loop only updated roots
 * that matched the scan, and read-modify-write deliberately preserves
 * unmatched entries to protect user-written content.
 *
 * The fix converges plugin-generated sub-packages like the main package:
 * unmatched roots whose pages array carries the generation marker are
 * dropped entirely — the current platform has no visible page left in
 * them, and keeping the root (even with other platforms' entries wrapped)
 * would ship an empty sub-package to this platform's build output whose
 * root directory does not even exist on disk. Dropping loses no state:
 * every platform rewrites its scanned entries on each run, so the other
 * platforms re-add the root on their next write. User-written
 * sub-packages carry no marker and stay untouched.
 *
 * Platform model follows pages-json-home-reorder.test.ts: the current
 * platform is injected through the PageContext constructor, while the
 * pre-seeded file represents other platforms' output.
 */

function writePage(pagesDir: string, name: string, macro: string): void {
  fs.writeFileSync(
    path.join(pagesDir, `${name}.vue`),
    [
      '<script lang="ts" setup>',
      macro,
      '</script>',
      '',
      `<template><div>${name}</div></template>`,
      '',
    ].join('\n'),
    'utf-8',
  )
}

describe('pages.json converges stale plugin-generated sub-packages', () => {
  let tmpDir: string
  let pagesJsonPath: string

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-subpkg-converge-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages')
    fs.mkdirSync(pagesDir, { recursive: true })

    writePage(pagesDir, 'index', 'definePage({ style: { navigationBarTitleText: \'home\' } });')

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')
  })

  beforeEach(() => {
    // Seed sub-packages as written by previous runs of other platforms,
    // covering every removal geometry in one file. The current platform
    // (mp-weixin) scans no sub-package here, so EVERY plugin-generated root
    // has zero visible pages for it and must be removed — including the
    // multi-platform ones, whose surviving entries would otherwise ship as
    // an empty sub-package shell in this platform's build output:
    // - pkg-gen-weixin (index 0, FIRST position): generated for MP-WEIXIN
    //   only; must be removed, and the user comment between its `}` and `,`
    //   (an after-value comment) must NOT leak onto the entry shifting into
    //   its slot
    // - pkg-gen-zero2 (index 1): also MP-WEIXIN-only, adjacent to the one
    //   above so the removal exercises two consecutive splices
    // - pkg-gen-mixed: generated, one H5 entry + one APP-only entry; other
    //   platforms still have pages here, but the current platform's view is
    //   empty, so the root is removed too (H5/APP re-add it on their next
    //   write)
    // - pkg-gen-strip: generated for H5 || MP-WEIXIN; same zero-visibility
    //   removal, carrying a plugins property that goes away with the root
    // - pkg-user: handwritten (no generation marker), with its own comment;
    //   must survive byte-for-byte including the comment attachment after
    //   every generated entry was spliced out around it
    // - pkg-gen-tail (LAST position): MP-WEIXIN-only; must be removed
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    {',
        '      "path": "pages/index",',
        '      "style": {',
        '        "navigationBarTitleText": "home"',
        '      }',
        '    }',
        '  ],',
        '  "subPackages": [',
        '    {',
        '      "root": "pkg-gen-weixin",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
        '        {',
        '          "path": "w1",',
        '          "style": {',
        '            "navigationBarTitleText": "w1"',
        '          }',
        '        }',
        '      ]',
        '    } /* stale note */,',
        '    {',
        '      "root": "pkg-gen-zero2",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
        '        {',
        '          "path": "z1",',
        '          "style": {',
        '            "navigationBarTitleText": "z1"',
        '          }',
        '        }',
        '      ]',
        '    },',
        '    {',
        '      "root": "pkg-gen-mixed",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '        {',
        '          "path": "p1",',
        '          "style": {',
        '            "navigationBarTitleText": "p1"',
        '          }',
        '        },',
        '        // #ifdef APP',
        '        {',
        '          "path": "p2",',
        '          "style": {',
        '            "navigationBarTitleText": "p2"',
        '          }',
        '        }',
        '        // #endif',
        '      ]',
        '    },',
        '    {',
        '      "root": "pkg-gen-strip",',
        '      "plugins": ["test-plugin"],',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN',
        '        {',
        '          "path": "p3",',
        '          "style": {',
        '            "navigationBarTitleText": "p3"',
        '          }',
        '        },',
        '        // #ifdef MP-WEIXIN',
        '        {',
        '          "path": "p4",',
        '          "style": {',
        '            "navigationBarTitleText": "p4"',
        '          }',
        '        }',
        '        // #endif',
        '      ]',
        '    },',
        '    // user maintained package',
        '    {',
        '      "root": "pkg-user",',
        '      "pages": [',
        '        {',
        '          "path": "u1",',
        '          "style": {',
        '            "navigationBarTitleText": "u1"',
        '          }',
        '        }',
        '      ]',
        '    },',
        '    {',
        '      "root": "pkg-gen-tail",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
        '        {',
        '          "path": "t1",',
        '          "style": {',
        '            "navigationBarTitleText": "t1"',
        '          }',
        '        }',
        '      ]',
        '    }',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  const run = async (): Promise<string> => {
    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()
    return fs.readFileSync(pagesJsonPath, 'utf-8')
  }

  it('removes every generated root invisible to the current platform and never touches handwritten packages', async () => {
    const content = await run()

    // Removed roots: first position, adjacent middle, multi-platform middle
    // entries, and last position — none of them has a page visible to
    // MP-WEIXIN, so all of them converge away entirely
    expect(content).not.toContain('"pkg-gen-weixin"')
    expect(content).not.toContain('"w1"')
    expect(content).not.toContain('"pkg-gen-zero2"')
    expect(content).not.toContain('"z1"')
    expect(content).not.toContain('"pkg-gen-mixed"')
    expect(content).not.toContain('"p1"')
    expect(content).not.toContain('"p2"')
    expect(content).not.toContain('"pkg-gen-strip"')
    expect(content).not.toContain('"p3"')
    expect(content).not.toContain('"p4"')
    // The plugins property seeded on pkg-gen-strip goes away with the root
    expect(content).not.toContain('"test-plugin"')
    expect(content).not.toContain('"pkg-gen-tail"')
    expect(content).not.toContain('"t1"')
    // The after-value comment of the removed first entry must not leak onto
    // the entry that shifted into its slot
    expect(content).not.toContain('stale note')

    // pkg-user carries no generation marker and stays untouched, with its
    // comment still attached directly above it even though every generated
    // sub-package around it was spliced out
    expect(content).toContain('"u1"')
    const commentPos = content.indexOf('// user maintained package')
    const userPos = content.indexOf('"pkg-user"')
    expect(commentPos).toBeGreaterThan(-1)
    expect(commentPos).toBeLessThan(userPos)

    // Output stays parseable with exactly the handwritten root surviving
    const parsed = cjParse(content) as CommentObject
    const subPackages = parsed.subPackages
    expect(Array.isArray(subPackages)).toBe(true)
    if (!Array.isArray(subPackages)) {
      return
    }
    const roots = subPackages
      .filter((p): p is CommentObject => typeof p === 'object' && p !== null)
      .map(p => p.root)
    expect(roots).toEqual(['pkg-user'])
  })

  it('keeps the output stable across consecutive runs', async () => {
    const first = await run()
    const second = await run()
    expect(second).toBe(first)
  })
})

describe('pipeline: skipped sub-package pages converge per platform', () => {
  // The cases below form a sequential cross-platform timeline sharing one
  // tmpDir: each run builds on the pages.json written by the previous one.
  let tmpDir: string
  let pkgDir: string
  let pagesJsonPath: string

  const options = {
    dir: 'src/pages',
    outDir: 'src',
    homePage: 'pages/index',
    subPackages: ['src/pkg'],
    dts: false,
  }

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-subpkg-pipeline-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages')
    pkgDir = path.join(tmpDir, 'src', 'pkg')
    fs.mkdirSync(pagesDir, { recursive: true })
    fs.mkdirSync(pkgDir, { recursive: true })

    writePage(pagesDir, 'index', 'definePage({ style: { navigationBarTitleText: \'home\' } });')
    writePage(
      pkgDir,
      'alipay-only',
      'definePage(({ platform }) => (platform === \'mp-weixin\' ? null : { style: { navigationBarTitleText: \'alipay only\' } }));',
    )

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  const run = async (platform: string): Promise<CommentObject> => {
    const ctx = new PageContext(options, tmpDir, platform)
    await ctx.updatePagesJSON()
    return cjParse(fs.readFileSync(pagesJsonPath, 'utf-8')) as CommentObject
  }

  const subRoots = (parsed: CommentObject): unknown[] =>
    Array.isArray(parsed.subPackages) ? parsed.subPackages : []

  it('writes the sub-package on platforms where the page exists', async () => {
    const parsed = await run('mp-alipay')
    const roots = subRoots(parsed)
    expect(roots.length).toBe(1)
    const pages = (roots[0] as CommentObject).pages
    expect(Array.isArray(pages)).toBe(true)
    if (!Array.isArray(pages)) {
      return
    }
    expect(pages.map(p => (p as CommentObject).path)).toEqual(['alipay-only'])
  })

  it('drops the root when the page is skipped on the current platform', async () => {
    const parsed = await run('mp-weixin')
    // The page is skipped on mp-weixin, so the sub-package has no page
    // visible to this platform. The root must be removed entirely:
    // keeping it (even with the MP-ALIPAY entry wrapped in #ifdef) would
    // ship an empty sub-package to the weixin build whose root directory
    // does not exist in the output. Dropping loses no state — mp-alipay
    // rewrites the root from its own scan (see the next case)
    expect(Array.isArray(parsed.subPackages)).toBe(true)
    expect(subRoots(parsed).length).toBe(0)
    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    expect(content).not.toContain('"alipay-only"')
    // The main package survives untouched
    expect(content).toContain('"pages/index"')
  })

  it('re-adds the root on the next write of a platform that still has pages', async () => {
    const parsed = await run('mp-alipay')
    // The scan produces the page again, so the root comes back bare under
    // the single-platform marker — proof that the earlier drop lost no state
    const roots = subRoots(parsed)
    expect(roots.length).toBe(1)
    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    expect(content).toContain('GENERATED BY UNI-PAGES, PLATFORM: MP-ALIPAY\n')
    expect(content).toContain('"alipay-only"')
    expect(content).not.toContain('#ifdef')
  })

  it('removes the root once no platform produces pages for it anymore', async () => {
    // Delete the page file, then run mp-alipay again: the scan misses the
    // root and convergence removes it
    fs.rmSync(path.join(pkgDir, 'alipay-only.vue'))

    const parsed = await run('mp-alipay')
    // Guard against a regression dropping the subPackages key entirely,
    // which an empty-array length check alone would not catch
    expect(Array.isArray(parsed.subPackages)).toBe(true)
    expect(subRoots(parsed).length).toBe(0)
    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    expect(content).not.toContain('"alipay-only"')

    // The main package survives the sub-package removal untouched
    expect(content).toContain('"pages/index"')
  })
})

describe('pipeline: a sub-package empty on the current platform stays out of its view', () => {
  // Regression for the PR #286 review finding: a sub-package whose pages
  // exist only on H5 and all opt out via definePage(null) on MP-WEIXIN.
  // resolvePlatformUnion used to collect platforms only from the entries
  // still present, so after the weixin run contributed zero pages the union
  // stayed 'H5' and the H5-only entry was judged to cover the full union and
  // emitted bare — leaking into the weixin conditional-compilation view
  // (bare entries are visible to every platform). The current platform must
  // always join the union. On top of that, a plugin-generated sub-package
  // with no page left for the current platform is dropped entirely: the
  // weixin build output contains no directory for it, so an app.json entry
  // (even one whose pages are all wrapped away) would point at nothing.
  let tmpDir: string
  let pagesJsonPath: string

  const options = {
    dir: 'src/pages',
    outDir: 'src',
    homePage: 'pages/index',
    subPackages: ['src/pkg'],
    dts: false,
  }

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-subpkg-empty-platform-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages')
    const pkgDir = path.join(tmpDir, 'src', 'pkg')
    fs.mkdirSync(pagesDir, { recursive: true })
    fs.mkdirSync(pkgDir, { recursive: true })

    writePage(pagesDir, 'index', 'definePage({ style: { navigationBarTitleText: \'home\' } });')
    writePage(
      pkgDir,
      'h5-only',
      'definePage(({ platform }) => (platform === \'mp-weixin\' ? null : { style: { navigationBarTitleText: \'h5 only\' } }));',
    )

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  const run = async (platform: string): Promise<string> => {
    const ctx = new PageContext(options, tmpDir, platform)
    await ctx.updatePagesJSON()
    return fs.readFileSync(pagesJsonPath, 'utf-8')
  }

  it('emits the sub-package bare while its only platform is the current one', async () => {
    const content = await run('h5')
    const segment = content.slice(content.indexOf('"pkg"'))
    expect(segment).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5\n')
    expect(segment).toContain('"h5-only"')
    expect(segment).not.toContain('#ifdef')
  })

  it('drops the sub-package entirely on the zero-contribution platform', async () => {
    const content = await run('mp-weixin')

    // No page of this sub-package is visible to MP-WEIXIN, so the root must
    // not survive in any form — a leftover root (bare or fully wrapped)
    // would ship an empty sub-package into the weixin build whose root
    // directory does not exist
    expect(content).not.toContain('"pkg"')
    expect(content).not.toContain('"h5-only"')
    // The main package survives untouched
    expect(content).toContain('"pages/index"')
    // Guard against a vacuous pass: subPackages must still serialize as an
    // (empty) array, not disappear from the output
    const parsed = cjParse(content) as CommentObject
    expect(Array.isArray(parsed.subPackages)).toBe(true)
  })

  it('stays byte-stable across consecutive zero-contribution runs', async () => {
    const first = fs.readFileSync(pagesJsonPath, 'utf-8')
    const second = await run('mp-weixin')
    expect(second).toBe(first)
  })

  it('re-adds the sub-package once its own platform re-runs', async () => {
    // The H5 run re-scans the page and rewrites the root bare — the earlier
    // drop lost no state
    const content = await run('h5')
    const segment = content.slice(content.indexOf('"pkg"'))
    expect(segment).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5\n')
    expect(segment).toContain('"h5-only"')
    expect(segment).not.toContain('#ifdef')
  })
})
