import { describe, expect, it } from 'vitest'
import { mergePagesJson } from '../packages/core/src'

/**
 * Direct tests of the pure pages.json merge seam.
 *
 * `mergePagesJson` owns the whole read-modify-write computation (multi
 * platform #ifdef merging, generation marker, home reordering, sub-package
 * convergence, serialization) behind a string-in/string-out interface, so
 * these cases assert on the generated content directly instead of setting up
 * temp directories or inspecting comment-json symbols.
 */

describe('mergePagesJson pure merge seam', () => {
  it('merges an identical entry across platforms without duplicating it', () => {
    // Seed shape of a legacy or user-edited file: one entry under the
    // generation marker, without the internal `type` marker
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
      '    {',
      '      "path": "pages/index/index",',
      '      "style": {',
      '        "navigationBarTitleText": "uni-app"',
      '      }',
      '    }',
      '  ],',
      '  "subPackages": []',
      '}',
      '',
    ].join('\n')

    const content = mergePagesJson(existing, {
      pages: [{
        path: 'pages/index/index',
        type: 'home',
        style: { navigationBarTitleText: 'uni-app' },
      }],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    // Both platforms fold into the default platform list: no #ifdef block and
    // exactly one entry (regression guard for issue #283)
    expect(content.match(/pages\/index\/index/g)).toHaveLength(1)
    expect(content).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN')
    expect(content).not.toContain('#ifdef')
    // The merged entry keeps the seeded file object, so no `type` marker
    // appears here
    expect(content).not.toContain('"type"')
  })

  it('keeps the type marker on freshly generated entries by design', () => {
    // Plugin-generated entries carry the internal `type` marker into
    // pages.json on purpose: it powers the home fallback in later runs
    const content = mergePagesJson('', {
      pages: [{ path: 'pages/index/index', type: 'home' }],
      subPackages: [],
    }, { platform: 'h5' })

    expect(content).toContain('"type": "home"')
  })

  it('keeps diverging entries behind platform #ifdef blocks', () => {
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
      '    {',
      '      "path": "pages/index/index",',
      '      "style": {',
      '        "navigationBarTitleText": "h5 title"',
      '      }',
      '    }',
      '  ],',
      '  "subPackages": []',
      '}',
      '',
    ].join('\n')

    const content = mergePagesJson(existing, {
      pages: [{
        path: 'pages/index/index',
        type: 'home',
        style: { navigationBarTitleText: 'weixin title' },
      }],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    expect(content).toContain('#ifdef H5')
    expect(content).toContain('h5 title')
    expect(content).toContain('weixin title')
    // The current platform becomes the default (no #ifdef wrapper) on a
    // tie, so only the other platform's entry sits inside an #ifdef block
    expect(content.match(/#ifdef/g)).toHaveLength(1)
    expect(content.match(/#endif/g)).toHaveLength(1)
    // The home entry was reordered to the first position by its type marker
    expect(content.indexOf('weixin title')).toBeLessThan(content.indexOf('h5 title'))
  })

  it('moves the home page to the first position by path', () => {
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
      '    {',
      '      "path": "pages/a/a"',
      '    },',
      '    {',
      '      "path": "pages/home/home"',
      '    }',
      '  ],',
      '  "subPackages": []',
      '}',
      '',
    ].join('\n')

    const content = mergePagesJson(existing, {
      pages: [
        { path: 'pages/a/a', type: 'page' },
        { path: 'pages/home/home', type: 'home' },
      ],
      subPackages: [],
      homePath: 'pages/home/home',
    }, { platform: 'h5' })

    expect(content.indexOf('pages/home/home')).toBeLessThan(content.indexOf('pages/a/a'))
    // The generation marker survives the reordering exactly once and stays
    // ahead of every page entry
    expect(content.match(/GENERATED BY UNI-PAGES/g)).toHaveLength(1)
    expect(content.indexOf('GENERATED BY UNI-PAGES')).toBeLessThan(content.indexOf('pages/home/home'))
  })

  it('converges plugin-generated sub-packages missing from this run', () => {
    const existing = [
      '{',
      '  "pages": [],',
      '  "subPackages": [',
      '    {',
      '      "root": "pages-sub",',
      '      "pages": [',
      '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
      '        {',
      '          "path": "pages/index"',
      '        }',
      '      ]',
      '    },',
      '    {',
      '      "root": "user-sub",',
      '      "pages": [',
      '        {',
      '          "path": "pages/keep"',
      '        }',
      '      ]',
      '    }',
      '  ]',
      '}',
      '',
    ].join('\n')

    // This run scans nothing on mp-weixin: the plugin-generated sub-package
    // (whose only platform is the current one) converges away entirely, the
    // user-written one stays untouched
    const content = mergePagesJson(existing, {
      pages: [],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    expect(content).not.toContain('pages-sub')
    expect(content).toContain('user-sub')
    expect(content).toContain('pages/keep')
  })

  it('applies the serialization format options', () => {
    const data = {
      pages: [{ path: 'pages/index/index', type: 'home' as const }],
      subPackages: [],
    }

    const minified = mergePagesJson('', data, { platform: 'h5', format: { minify: true } })
    expect(minified).not.toContain('\n')
    // Single-line JSON cannot carry comments: the generation marker is
    // dropped and multi-platform tracking restarts on the next run
    expect(minified).not.toContain('GENERATED BY UNI-PAGES')

    const tabbed = mergePagesJson('', data, { platform: 'h5', format: { indent: '\t', insertFinalNewline: true } })
    expect(tabbed).toContain('\t')
    expect(tabbed.endsWith('\n')).toBe(true)

    const crlf = mergePagesJson('', data, { platform: 'h5', format: { eol: '\r\n' } })
    expect(crlf).toContain('\r\n')
    // Every line break is CRLF: no bare LF survives
    expect(crlf.replaceAll('\r\n', '').includes('\n')).toBe(false)
  })
})
