import type { CommentObject } from 'comment-json'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parse as cjParse } from 'comment-json'
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { PageContext } from '../packages/core/src'

/**
 * writePagesJson 中首页重排的回归覆盖。
 *
 * 当首页条目在合并后的数组中不在首位时，三个既有缺陷叠加起来破坏
 * pages.json：
 *
 * 1. `CommentArray#splice`/`unshift` 只重排幸存元素的注释符号：被移除
 *    条目的注释滞留在旧下标上，最终挂到移入该槽位的元素上。
 * 2. 合并后的条目可能保留从 pages.json 读出的、没有内部 `type` 标记
 *    的对象（本用例的种子就是这样），`type === 'home'` 查找因此永远
 *    不命中，重排静默地没有执行。
 * 3. 首个合并条目需要 `#ifdef` 块时，赋值 `before:0` 会替换掉
 *    GENERATED 标记而非追加。
 *
 * 平台模型与 concurrent-pages-json.test.ts 一致：当前平台
 * （mp-weixin）通过 PageContext 构造函数注入，预置文件代表另一个
 * 终端的输出。
 */

function writePage(pagesDir: string, name: string, title: string): void {
  fs.writeFileSync(
    path.join(pagesDir, `${name}.vue`),
    [
      '<script lang="ts" setup>',
      `definePage(() => ({ style: { navigationBarTitleText: '${title}' } }));`,
      '</script>',
      '',
      `<template><div>${title}</div></template>`,
      '',
    ].join('\n'),
    'utf-8',
  )
}

describe('pages.json home page reordering keeps comment attachment', () => {
  let tmpDir: string
  let srcDir: string
  let pagesJsonPath: string

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-home-reorder-'))
    srcDir = path.join(tmpDir, 'src')
    const pagesDir = path.join(srcDir, 'pages')
    fs.mkdirSync(pagesDir, { recursive: true })

    writePage(pagesDir, 'index', 'home')
    writePage(pagesDir, 'about', 'about')
    writePage(pagesDir, 'settings', 'settings')
    writePage(pagesDir, 'app-only', 'app only')

    pagesJsonPath = path.join(srcDir, 'pages.json')
  })

  beforeEach(() => {
    // 按另一个平台的运行结果预置 pages.json，首页条目放在最后，
    // 强制合并结果需要重排。首页条目与扫描到的页面解析结果一致，
    // 因此合并为覆盖所有已记录平台（APP、H5、MP-WEIXIN）的单个条目。
    //
    // 首个合并条目（app-only）只覆盖全集的子集并被包裹，
    // 过去这会覆盖 before:0 上的 GENERATED 标记。
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    // #ifdef APP',
        '    {',
        '      "path": "pages/app-only",',
        '      "style": {',
        '        "navigationBarTitleText": "app only"',
        '      }',
        '    },',
        '    // #endif',
        '    {',
        '      "path": "pages/about",',
        '      "style": {',
        '        "navigationBarTitleText": "about"',
        '      }',
        '    },',
        '    {',
        '      "path": "pages/settings",',
        '      "style": {',
        '        "navigationBarTitleText": "settings"',
        '      }',
        '    },',
        '    // #ifdef H5 || APP',
        '    {',
        '      "path": "pages/index",',
        '      "style": {',
        '        "navigationBarTitleText": "home"',
        '      }',
        '    }',
        '    // #endif',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it('moves home first without stranding comments or overwriting the generation marker', async () => {
    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()

    const content = fs.readFileSync(pagesJsonPath, 'utf-8')

    // 合并后的首页条目存在于 APP、H5 与 MP-WEIXIN，因此覆盖整个平台
    // 全集并保持在下标 0 不被包裹。app-only 与 about/settings 只覆盖
    // 子集，保留各自的 #ifdef 块；它们的注释令牌必须跟随重排而不是
    // 滞留在邻居上，生成标记也必须保留在最顶部——即使首个合并条目
    // （app-only）是被包裹的。按位置检查完整布局：
    //   marker, pages/index,
    //   #ifdef (app-only), pages/app-only, #endif,
    //   #ifdef (about), pages/about, #endif,
    //   #ifdef (settings), pages/settings, #endif
    const markerPos = content.indexOf('GENERATED BY UNI-PAGES, PLATFORM: APP || H5 || MP-WEIXIN')
    const indexPos = content.indexOf('"pages/index"')
    const appIfdefPos = content.indexOf('#ifdef APP || MP-WEIXIN')
    const appPos = content.indexOf('"pages/app-only"')
    const appEndifPos = content.indexOf('#endif', appIfdefPos)
    const aboutIfdefPos = content.indexOf('#ifdef H5 || MP-WEIXIN')
    const aboutPos = content.indexOf('"pages/about"')
    const aboutEndifPos = content.indexOf('#endif', aboutPos)
    const settingsIfdefPos = content.indexOf('#ifdef H5 || MP-WEIXIN', aboutEndifPos)
    const settingsPos = content.indexOf('"pages/settings"')
    const settingsEndifPos = content.indexOf('#endif', settingsPos)

    expect(markerPos).toBeGreaterThan(-1)
    expect(markerPos).toBeLessThan(indexPos)
    expect(indexPos).toBeLessThan(appIfdefPos)
    expect(appIfdefPos).toBeLessThan(appPos)
    expect(appPos).toBeLessThan(appEndifPos)
    expect(appEndifPos).toBeLessThan(aboutIfdefPos)
    expect(aboutIfdefPos).toBeLessThan(aboutPos)
    expect(aboutPos).toBeLessThan(aboutEndifPos)
    expect(aboutEndifPos).toBeLessThan(settingsIfdefPos)
    expect(settingsIfdefPos).toBeLessThan(settingsPos)
    expect(settingsPos).toBeLessThan(settingsEndifPos)

    // 输出必须仍可解析，且首页是第一个条目。
    const parsed = cjParse(content) as CommentObject
    const pages = parsed.pages
    expect(Array.isArray(pages)).toBe(true)
    if (!Array.isArray(pages)) {
      return
    }
    const paths = pages
      .filter((p): p is CommentObject => typeof p === 'object' && p !== null)
      .map(p => p.path)
    expect(paths).toEqual(['pages/index', 'pages/app-only', 'pages/about', 'pages/settings'])
  })

  it('keeps the output stable across consecutive runs', async () => {
    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()
    const first = fs.readFileSync(pagesJsonPath, 'utf-8')

    // 第二次运行读回生成的文件；生成标记必须仍能在 before:0 找到，
    // 布局不得翻腾。
    await ctx.updatePagesJSON()
    const second = fs.readFileSync(pagesJsonPath, 'utf-8')

    expect(second).toBe(first)
  })

  it('keeps the #ifdef block of entries behind home intact when home is not last', async () => {
    // 首页在种子中间：把它 splice 出来后，comment-json 会把后续条目
    // 的注释下移到它的旧槽位。删除滞留符号必须发生在 splice 之前，
    // 否则会破坏移入该槽位的条目的 #ifdef/#endif。
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    {',
        '      "path": "pages/about",',
        '      "style": {',
        '        "navigationBarTitleText": "about"',
        '      }',
        '    },',
        '    {',
        '      "path": "pages/index",',
        '      "style": {',
        '        "navigationBarTitleText": "home"',
        '      }',
        '    },',
        '    {',
        '      "path": "pages/settings",',
        '      "style": {',
        '        "navigationBarTitleText": "settings"',
        '      }',
        '    },',
        '    // #ifdef APP',
        '    {',
        '      "path": "pages/app-only",',
        '      "style": {',
        '        "navigationBarTitleText": "app only"',
        '      }',
        '    }',
        '    // #endif',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )

    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()

    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    // 没有变体覆盖整个平台全集，因此每个条目都保持包裹；首页在自己的
    // 块内移到最前，app-only 尽管排在首页旧槽位之后，也必须保留其
    // 重新计算出的 #ifdef 块。
    const markerPos = content.indexOf('GENERATED BY UNI-PAGES, PLATFORM: APP || H5 || MP-WEIXIN')
    const homeIfdefPos = content.indexOf('#ifdef H5 || MP-WEIXIN')
    const indexPos = content.indexOf('"pages/index"')
    const indexEndifPos = content.indexOf('#endif', indexPos)
    const aboutIfdefPos = content.indexOf('#ifdef H5 || MP-WEIXIN', indexEndifPos)
    const aboutPos = content.indexOf('"pages/about"')
    const aboutEndifPos = content.indexOf('#endif', aboutPos)
    const settingsIfdefPos = content.indexOf('#ifdef H5 || MP-WEIXIN', aboutEndifPos)
    const settingsPos = content.indexOf('"pages/settings"')
    const appIfdefPos = content.indexOf('#ifdef APP || MP-WEIXIN')
    const appPos = content.indexOf('"pages/app-only"')
    const appEndifPos = content.indexOf('#endif', appPos)

    expect(markerPos).toBeGreaterThan(-1)
    expect(markerPos).toBeLessThan(homeIfdefPos)
    expect(homeIfdefPos).toBeLessThan(indexPos)
    expect(indexPos).toBeLessThan(indexEndifPos)
    expect(indexEndifPos).toBeLessThan(aboutIfdefPos)
    expect(aboutIfdefPos).toBeLessThan(aboutPos)
    expect(aboutPos).toBeLessThan(aboutEndifPos)
    expect(aboutEndifPos).toBeLessThan(settingsIfdefPos)
    expect(settingsIfdefPos).toBeLessThan(settingsPos)
    expect(settingsPos).toBeLessThan(appIfdefPos)
    expect(appIfdefPos).toBeLessThan(appPos)
    expect(appPos).toBeLessThan(appEndifPos)

    const parsed = cjParse(content) as CommentObject
    const pages = parsed.pages
    expect(Array.isArray(pages)).toBe(true)
    if (!Array.isArray(pages)) {
      return
    }
    const paths = pages
      .filter((p): p is CommentObject => typeof p === 'object' && p !== null)
      .map(p => p.path)
    expect(paths).toEqual(['pages/index', 'pages/about', 'pages/settings', 'pages/app-only'])
  })

  it('stays stable when platform usage counts tie', async () => {
    // 每个平台集两个条目（2:2 并列）。过去默认平台按 map 插入顺序挑
    // 选，首页重排在两次运行间改变这个顺序，包裹关系来回翻转。平台
    // 全集按构造与顺序无关，因此第二次运行必须字节相同。
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    // #ifdef H5',
        '    {',
        '      "path": "pages/about",',
        '      "style": {',
        '        "navigationBarTitleText": "about"',
        '      }',
        '    },',
        '    // #endif',
        '    // #ifdef APP',
        '    {',
        '      "path": "pages/index",',
        '      "style": {',
        '        "navigationBarTitleText": "home"',
        '      }',
        '    },',
        '    // #endif',
        '    // #ifdef H5',
        '    {',
        '      "path": "pages/settings",',
        '      "style": {',
        '        "navigationBarTitleText": "settings"',
        '      }',
        '    },',
        '    // #endif',
        '    // #ifdef APP',
        '    {',
        '      "path": "pages/app-only",',
        '      "style": {',
        '        "navigationBarTitleText": "app only"',
        '      }',
        '    }',
        '    // #endif',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )

    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()
    const first = fs.readFileSync(pagesJsonPath, 'utf-8')

    // 基于全集的标记与上一次运行产生的条目顺序无关
    expect(first).toContain('GENERATED BY UNI-PAGES, PLATFORM: APP || H5 || MP-WEIXIN')

    await ctx.updatePagesJSON()
    const second = fs.readFileSync(pagesJsonPath, 'utf-8')
    expect(second).toBe(first)
  })
})
