import type { CommentObject } from 'comment-json'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parse as cjParse } from 'comment-json'
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { PageContext } from '../packages/core/src'

/**
 * Regression coverage for the home page reordering in writePagesJson.
 *
 * Three pre-existing issues combined to corrupt pages.json when the home
 * entry was not already first in the merged array:
 *
 * 1. `CommentArray#splice`/`unshift` only re-index the surviving elements'
 *    comment symbols: the removed entry's comments stay stranded at its old
 *    index and end up attached to whatever element moves into that slot.
 * 2. A merged entry may keep the object read from pages.json without the
 *    internal `type` marker (this seed does), so the `type === 'home'`
 *    lookup never matched and the reordering silently did not run.
 * 3. When the first merged entry needed an `#ifdef` block, assigning
 *    `before:0` replaced the GENERATED marker instead of appending to it.
 *
 * Platform model follows concurrent-pages-json.test.ts: the current platform
 * (mp-weixin) is injected through the PageContext constructor, while the
 * pre-seeded file represents another terminal's output.
 */

function writePage(pagesDir: string, name: string, title: string): void {
  fs.writeFileSync(
    path.join(pagesDir, `${name}.vue`),
    [
      '<script lang="ts" setup>',
      `definePage(() => ({ style: { navigationBarTitleText: '${title}' } }));`,
      '</script>',
      '',
      `<template><div>${title}</div></template>`,
      '',
    ].join('\n'),
    'utf-8',
  )
}

describe('pages.json home page reordering keeps comment attachment', () => {
  let tmpDir: string
  let srcDir: string
  let pagesJsonPath: string

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-home-reorder-'))
    srcDir = path.join(tmpDir, 'src')
    const pagesDir = path.join(srcDir, 'pages')
    fs.mkdirSync(pagesDir, { recursive: true })

    writePage(pagesDir, 'index', 'home')
    writePage(pagesDir, 'about', 'about')
    writePage(pagesDir, 'settings', 'settings')
    writePage(pagesDir, 'app-only', 'app only')

    pagesJsonPath = path.join(srcDir, 'pages.json')
  })

  beforeEach(() => {
    // Seed pages.json as written by another platform's run, with the home
    // entry LAST so the merge result requires reordering. The home entry is
    // identical to what the scanned page resolves to, so it merges into a
    // single item covering every recorded platform (APP, H5, MP-WEIXIN).
    //
    // The first merged entry (app-only) only covers a subset of the union
    // and is wrapped, which used to overwrite the GENERATED marker at
    // before:0.
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    // #ifdef APP',
        '    {',
        '      "path": "pages/app-only",',
        '      "style": {',
        '        "navigationBarTitleText": "app only"',
        '      }',
        '    },',
        '    // #endif',
        '    {',
        '      "path": "pages/about",',
        '      "style": {',
        '        "navigationBarTitleText": "about"',
        '      }',
        '    },',
        '    {',
        '      "path": "pages/settings",',
        '      "style": {',
        '        "navigationBarTitleText": "settings"',
        '      }',
        '    },',
        '    // #ifdef H5 || APP',
        '    {',
        '      "path": "pages/index",',
        '      "style": {',
        '        "navigationBarTitleText": "home"',
        '      }',
        '    }',
        '    // #endif',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it('moves home first without stranding comments or overwriting the generation marker', async () => {
    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()

    const content = fs.readFileSync(pagesJsonPath, 'utf-8')

    // The merged home entry exists on APP, H5 and MP-WEIXIN, so it covers
    // the full platform union and stays unwrapped at index 0. app-only and
    // about/settings only cover subsets and keep their #ifdef blocks; their
    // comment tokens must follow the reordering instead of stranding on a
    // neighbour, and the generation marker must survive at the very top even
    // though the first merged entry (app-only) is wrapped. Check the full
    // layout positionally:
    //   marker, pages/index,
    //   #ifdef (app-only), pages/app-only, #endif,
    //   #ifdef (about), pages/about, #endif,
    //   #ifdef (settings), pages/settings, #endif
    const markerPos = content.indexOf('GENERATED BY UNI-PAGES, PLATFORM: APP || H5 || MP-WEIXIN')
    const indexPos = content.indexOf('"pages/index"')
    const appIfdefPos = content.indexOf('#ifdef APP || MP-WEIXIN')
    const appPos = content.indexOf('"pages/app-only"')
    const appEndifPos = content.indexOf('#endif', appIfdefPos)
    const aboutIfdefPos = content.indexOf('#ifdef H5 || MP-WEIXIN')
    const aboutPos = content.indexOf('"pages/about"')
    const aboutEndifPos = content.indexOf('#endif', aboutPos)
    const settingsIfdefPos = content.indexOf('#ifdef H5 || MP-WEIXIN', aboutEndifPos)
    const settingsPos = content.indexOf('"pages/settings"')
    const settingsEndifPos = content.indexOf('#endif', settingsPos)

    expect(markerPos).toBeGreaterThan(-1)
    expect(markerPos).toBeLessThan(indexPos)
    expect(indexPos).toBeLessThan(appIfdefPos)
    expect(appIfdefPos).toBeLessThan(appPos)
    expect(appPos).toBeLessThan(appEndifPos)
    expect(appEndifPos).toBeLessThan(aboutIfdefPos)
    expect(aboutIfdefPos).toBeLessThan(aboutPos)
    expect(aboutPos).toBeLessThan(aboutEndifPos)
    expect(aboutEndifPos).toBeLessThan(settingsIfdefPos)
    expect(settingsIfdefPos).toBeLessThan(settingsPos)
    expect(settingsPos).toBeLessThan(settingsEndifPos)

    // Output must stay parseable, with home as the first entry.
    const parsed = cjParse(content) as CommentObject
    const pages = parsed.pages
    expect(Array.isArray(pages)).toBe(true)
    if (!Array.isArray(pages)) {
      return
    }
    const paths = pages
      .filter((p): p is CommentObject => typeof p === 'object' && p !== null)
      .map(p => p.path)
    expect(paths).toEqual(['pages/index', 'pages/app-only', 'pages/about', 'pages/settings'])
  })

  it('keeps the output stable across consecutive runs', async () => {
    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()
    const first = fs.readFileSync(pagesJsonPath, 'utf-8')

    // A second run reads the generated file back; the generation marker must
    // still be discoverable at before:0 and the layout must not churn.
    await ctx.updatePagesJSON()
    const second = fs.readFileSync(pagesJsonPath, 'utf-8')

    expect(second).toBe(first)
  })

  it('keeps the #ifdef block of entries behind home intact when home is not last', async () => {
    // Home in the middle of the seed: after splicing it out, comment-json
    // shifts the following entries' comments down into its old slot. Deleting
    // the stranded symbols must happen BEFORE the splice, otherwise this
    // destroys the #ifdef/#endif of the entry that moved into that slot.
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    {',
        '      "path": "pages/about",',
        '      "style": {',
        '        "navigationBarTitleText": "about"',
        '      }',
        '    },',
        '    {',
        '      "path": "pages/index",',
        '      "style": {',
        '        "navigationBarTitleText": "home"',
        '      }',
        '    },',
        '    {',
        '      "path": "pages/settings",',
        '      "style": {',
        '        "navigationBarTitleText": "settings"',
        '      }',
        '    },',
        '    // #ifdef APP',
        '    {',
        '      "path": "pages/app-only",',
        '      "style": {',
        '        "navigationBarTitleText": "app only"',
        '      }',
        '    }',
        '    // #endif',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )

    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()

    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    // No variant covers the full platform union, so every entry stays
    // wrapped; home moves first inside its own block and app-only must keep
    // its recomputed #ifdef block even though it sat behind home's old slot.
    const markerPos = content.indexOf('GENERATED BY UNI-PAGES, PLATFORM: APP || H5 || MP-WEIXIN')
    const homeIfdefPos = content.indexOf('#ifdef H5 || MP-WEIXIN')
    const indexPos = content.indexOf('"pages/index"')
    const indexEndifPos = content.indexOf('#endif', indexPos)
    const aboutIfdefPos = content.indexOf('#ifdef H5 || MP-WEIXIN', indexEndifPos)
    const aboutPos = content.indexOf('"pages/about"')
    const aboutEndifPos = content.indexOf('#endif', aboutPos)
    const settingsIfdefPos = content.indexOf('#ifdef H5 || MP-WEIXIN', aboutEndifPos)
    const settingsPos = content.indexOf('"pages/settings"')
    const appIfdefPos = content.indexOf('#ifdef APP || MP-WEIXIN')
    const appPos = content.indexOf('"pages/app-only"')
    const appEndifPos = content.indexOf('#endif', appPos)

    expect(markerPos).toBeGreaterThan(-1)
    expect(markerPos).toBeLessThan(homeIfdefPos)
    expect(homeIfdefPos).toBeLessThan(indexPos)
    expect(indexPos).toBeLessThan(indexEndifPos)
    expect(indexEndifPos).toBeLessThan(aboutIfdefPos)
    expect(aboutIfdefPos).toBeLessThan(aboutPos)
    expect(aboutPos).toBeLessThan(aboutEndifPos)
    expect(aboutEndifPos).toBeLessThan(settingsIfdefPos)
    expect(settingsIfdefPos).toBeLessThan(settingsPos)
    expect(settingsPos).toBeLessThan(appIfdefPos)
    expect(appIfdefPos).toBeLessThan(appPos)
    expect(appPos).toBeLessThan(appEndifPos)

    const parsed = cjParse(content) as CommentObject
    const pages = parsed.pages
    expect(Array.isArray(pages)).toBe(true)
    if (!Array.isArray(pages)) {
      return
    }
    const paths = pages
      .filter((p): p is CommentObject => typeof p === 'object' && p !== null)
      .map(p => p.path)
    expect(paths).toEqual(['pages/index', 'pages/about', 'pages/settings', 'pages/app-only'])
  })

  it('stays stable when platform usage counts tie', async () => {
    // Two entries per platform set (2:2 tie). The default platform used to be
    // picked from map insertion order, and the home reordering changed that
    // order between runs, flipping the wrapping back and forth. The platform
    // union is order-independent by construction, so the second run must be
    // byte-identical.
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    // #ifdef H5',
        '    {',
        '      "path": "pages/about",',
        '      "style": {',
        '        "navigationBarTitleText": "about"',
        '      }',
        '    },',
        '    // #endif',
        '    // #ifdef APP',
        '    {',
        '      "path": "pages/index",',
        '      "style": {',
        '        "navigationBarTitleText": "home"',
        '      }',
        '    },',
        '    // #endif',
        '    // #ifdef H5',
        '    {',
        '      "path": "pages/settings",',
        '      "style": {',
        '        "navigationBarTitleText": "settings"',
        '      }',
        '    },',
        '    // #endif',
        '    // #ifdef APP',
        '    {',
        '      "path": "pages/app-only",',
        '      "style": {',
        '        "navigationBarTitleText": "app only"',
        '      }',
        '    }',
        '    // #endif',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )

    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()
    const first = fs.readFileSync(pagesJsonPath, 'utf-8')

    // The union-based marker is independent of the entry order the previous
    // run produced
    expect(first).toContain('GENERATED BY UNI-PAGES, PLATFORM: APP || H5 || MP-WEIXIN')

    await ctx.updatePagesJSON()
    const second = fs.readFileSync(pagesJsonPath, 'utf-8')
    expect(second).toBe(first)
  })
})
