import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { mergePagesJson, PageContext } from '../packages/core/src'

/**
 * Direct tests of the pure pages.json merge seam.
 *
 * `mergePagesJson` owns the whole read-modify-write computation (multi
 * platform #ifdef merging, generation marker, home reordering, sub-package
 * convergence, serialization) behind a string-in/string-out interface, so
 * these cases assert on the generated content directly instead of setting up
 * temp directories or inspecting comment-json symbols.
 */

describe('mergePagesJson pure merge seam', () => {
  it('merges an identical entry across platforms without duplicating it', () => {
    // Seed shape of a legacy or user-edited file: one entry under the
    // generation marker, without the internal `type` marker
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
      '    {',
      '      "path": "pages/index/index",',
      '      "style": {',
      '        "navigationBarTitleText": "uni-app"',
      '      }',
      '    }',
      '  ],',
      '  "subPackages": []',
      '}',
      '',
    ].join('\n')

    const content = mergePagesJson(existing, {
      pages: [{
        path: 'pages/index/index',
        type: 'home',
        style: { navigationBarTitleText: 'uni-app' },
      }],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    // Both platforms fold into the default platform list: no #ifdef block and
    // exactly one entry (regression guard for issue #283)
    expect(content.match(/pages\/index\/index/g)).toHaveLength(1)
    expect(content).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN')
    expect(content).not.toContain('#ifdef')
    // The merged entry keeps the seeded file object, so no `type` marker
    // appears here
    expect(content).not.toContain('"type"')
  })

  it('keeps the type marker on freshly generated entries by design', () => {
    // Plugin-generated entries carry the internal `type` marker into
    // pages.json on purpose: it powers the home fallback in later runs
    const content = mergePagesJson('', {
      pages: [{ path: 'pages/index/index', type: 'home' }],
      subPackages: [],
    }, { platform: 'h5' })

    expect(content).toContain('"type": "home"')
  })

  it('keeps diverging entries behind platform #ifdef blocks', () => {
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
      '    {',
      '      "path": "pages/index/index",',
      '      "style": {',
      '        "navigationBarTitleText": "h5 title"',
      '      }',
      '    }',
      '  ],',
      '  "subPackages": []',
      '}',
      '',
    ].join('\n')

    const content = mergePagesJson(existing, {
      pages: [{
        path: 'pages/index/index',
        type: 'home',
        style: { navigationBarTitleText: 'weixin title' },
      }],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    expect(content).toContain('#ifdef H5')
    expect(content).toContain('#ifdef MP-WEIXIN')
    expect(content).toContain('h5 title')
    expect(content).toContain('weixin title')
    // Neither variant covers the full platform union ('H5 || MP-WEIXIN'),
    // so both stay wrapped: unwrapping one would leak it into the other
    // platform's conditional-compilation view
    expect(content.match(/#ifdef/g)).toHaveLength(2)
    expect(content.match(/#endif/g)).toHaveLength(2)
    // Each block wraps its own platform's variant, not the other one's
    expect(content.indexOf('#ifdef H5')).toBeLessThan(content.indexOf('h5 title'))
    expect(content.indexOf('#ifdef MP-WEIXIN')).toBeLessThan(content.indexOf('weixin title'))
    // The home entry was reordered to the first position by its type marker
    expect(content.indexOf('weixin title')).toBeLessThan(content.indexOf('h5 title'))
  })

  it('moves the home page to the first position by path', () => {
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
      '    {',
      '      "path": "pages/a/a"',
      '    },',
      '    {',
      '      "path": "pages/home/home"',
      '    }',
      '  ],',
      '  "subPackages": []',
      '}',
      '',
    ].join('\n')

    const content = mergePagesJson(existing, {
      pages: [
        { path: 'pages/a/a', type: 'page' },
        { path: 'pages/home/home', type: 'home' },
      ],
      subPackages: [],
      homePath: 'pages/home/home',
    }, { platform: 'h5' })

    expect(content.indexOf('pages/home/home')).toBeLessThan(content.indexOf('pages/a/a'))
    // The generation marker survives the reordering exactly once and stays
    // ahead of every page entry
    expect(content.match(/GENERATED BY UNI-PAGES/g)).toHaveLength(1)
    expect(content.indexOf('GENERATED BY UNI-PAGES')).toBeLessThan(content.indexOf('pages/home/home'))
  })

  it('converges plugin-generated sub-packages missing from this run', () => {
    const existing = [
      '{',
      '  "pages": [],',
      '  "subPackages": [',
      '    {',
      '      "root": "pages-sub",',
      '      "pages": [',
      '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
      '        {',
      '          "path": "pages/index"',
      '        }',
      '      ]',
      '    },',
      '    {',
      '      "root": "user-sub",',
      '      "pages": [',
      '        {',
      '          "path": "pages/keep"',
      '        }',
      '      ]',
      '    }',
      '  ]',
      '}',
      '',
    ].join('\n')

    // This run scans nothing on mp-weixin: the plugin-generated sub-package
    // (whose only platform is the current one) converges away entirely, the
    // user-written one stays untouched
    const content = mergePagesJson(existing, {
      pages: [],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    expect(content).not.toContain('pages-sub')
    expect(content).toContain('user-sub')
    expect(content).toContain('pages/keep')
  })

  it('applies the serialization format options', () => {
    const data = {
      pages: [{ path: 'pages/index/index', type: 'home' as const }],
      subPackages: [],
    }

    const minified = mergePagesJson('', data, { platform: 'h5', format: { minify: true } })
    expect(minified).not.toContain('\n')
    // Single-line JSON cannot carry comments: the generation marker is
    // dropped and multi-platform tracking restarts on the next run
    expect(minified).not.toContain('GENERATED BY UNI-PAGES')

    const tabbed = mergePagesJson('', data, { platform: 'h5', format: { indent: '\t', insertFinalNewline: true } })
    expect(tabbed).toContain('\t')
    expect(tabbed.endsWith('\n')).toBe(true)

    const crlf = mergePagesJson('', data, { platform: 'h5', format: { eol: '\r\n' } })
    expect(crlf).toContain('\r\n')
    // Every line break is CRLF: no bare LF survives
    expect(crlf.replaceAll('\r\n', '').includes('\n')).toBe(false)
  })

  it('documents #ifndef blocks: the condition is ignored, visibility follows the generation marker', () => {
    // mergePlatformItems only recognizes #ifdef blocks; a #ifndef condition
    // is never evaluated. The wrapped entry inherits the platform set
    // recorded by the generation marker (minus the current platform) and is
    // rewrapped as #ifdef on output. When the negated platform is absent
    // from the marker's union, the entry must still appear in that
    // platform's view per #ifndef semantics — the current output loses it,
    // and this test pins that status quo until #ifndef support lands.
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN',
      '    {',
      '      "path": "pages/index",',
      '      "type": "home"',
      '    },',
      '    // #ifndef MP-ALIPAY',
      '    {',
      '      "path": "pages/other"',
      '    }',
      '    // #endif',
      '  ]',
      '}',
    ].join('\n')

    const merged = mergePagesJson(existing, {
      pages: [{ path: 'pages/index', type: 'home' as const }],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    // The #ifndef wrapper is rewritten from the marker's platform set
    expect(merged).toContain('// #ifdef H5')
    expect(merged).not.toContain('#ifndef')

    // MP-ALIPAY never enters the marker's union, so the entry's new wrapper
    // hides it there — diverging from true #ifndef MP-ALIPAY semantics
    expect(merged).not.toContain('MP-ALIPAY')
  })
})

describe('page metadata merge does not leak style across runs', () => {
  it('keeps cached page style clean when a config override disappears', async () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-merge-leak-'))
    try {
      const pagesDir = path.join(tmpDir, 'src', 'pages', 'index')
      fs.mkdirSync(pagesDir, { recursive: true })
      fs.writeFileSync(
        path.join(pagesDir, 'index.vue'),
        [
          '<script lang="ts" setup>',
          'definePage(() => ({ style: { navigationBarTitleText: \'home\' } }));',
          '</script>',
          '',
          '<template><div>home</div></template>',
          '',
        ].join('\n'),
        'utf-8',
      )

      // Same context across both runs: Page instances (and their cached
      // meta style objects) are reused, so any in-place mutation of those
      // objects survives into the second run
      const ctx = new PageContext({ dir: 'src/pages', dts: false }, tmpDir, 'h5')

      ctx.pagesGlobConfig = {
        pages: [{ path: 'pages/index/index', style: { enablePullDownRefresh: true } }],
      }
      await ctx.scanAndMerge()
      expect(ctx.resolveRoutes()).toContain('enablePullDownRefresh')

      // The override disappears: the generated entry must fall back to its
      // own style without residue from the previous run
      ctx.pagesGlobConfig = {}
      await ctx.scanAndMerge()
      const routes = ctx.resolveRoutes()
      expect(routes).toContain('navigationBarTitleText')
      expect(routes).not.toContain('enablePullDownRefresh')
    }
    finally {
      fs.rmSync(tmpDir, { recursive: true, force: true })
    }
  })
})
