import type { CommentObject } from 'comment-json'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parse as cjParse } from 'comment-json'
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'

/**
 * Regression coverage for comment-json v5 blank line handling.
 *
 * comment-json v5 emits `BlankLine` tokens (without a `value` property) when
 * the parsed JSON contains blank lines — exactly what a manually formatted
 * pages.json looks like. `mergePlatformItems` used to assume every token in a
 * `before:N` comment array carries `value` and crashed with
 * `Cannot read properties of undefined (reading 'trim')`.
 *
 * Platform model follows concurrent-pages-json.test.ts: `UNI_PLATFORM` is set
 * before importing PageContext so the current process models mp-weixin, while
 * the pre-seeded file represents another terminal's (H5) output.
 */

// Set BEFORE importing context.ts, which captures `platform` from uni-env.
process.env.UNI_PLATFORM = 'mp-weixin'

// Dynamic import so the env above is in place when the module loads.
const { PageContext } = await import('../packages/core/src')

describe('pages.json with blank lines (comment-json v5 BlankLine tokens)', () => {
  let tmpDir: string
  let srcDir: string
  let pagesJsonPath: string

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-blank-lines-'))
    srcDir = path.join(tmpDir, 'src')
    const pagesDir = path.join(srcDir, 'pages')
    fs.mkdirSync(pagesDir, { recursive: true })

    fs.writeFileSync(
      path.join(pagesDir, 'index.vue'),
      [
        '<script lang="ts" setup>',
        'definePage(() => ({ style: { navigationBarTitleText: \'home\' } }));',
        '</script>',
        '',
        '<template><div>home</div></template>',
        '',
      ].join('\n'),
      'utf-8',
    )

    pagesJsonPath = path.join(srcDir, 'pages.json')
  })

  beforeEach(() => {
    // Seed a manually formatted pages.json: blank lines around the generation
    // marker, around the conditional compilation comments, and between items.
    // Each blank line becomes a BlankLine token in some `before:N` array.
    //
    // The seeded `pages/index` entry is identical to what the scanned page
    // resolves to, so it merges into a single item that stays first in the
    // result. This keeps the test focused on blank line handling; the home
    // reordering in generatePagesJSON is covered separately by
    // pages-json-home-reorder.test.ts.
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '',
        '    {',
        '      "path": "pages/index",',
        '      "style": {',
        '        "navigationBarTitleText": "home"',
        '      }',
        '    },',
        '',
        '    // #ifdef H5',
        '    {',
        '      "path": "pages/h5-only",',
        '      "style": {',
        '        "navigationBarTitleText": "h5 only"',
        '      }',
        '    }',
        '    // #endif',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it('merges without crashing and keeps other platforms\' entries', async () => {
    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
    )
    // Before the BlankLine guard this threw inside mergePlatformItems.
    await ctx.updatePagesJSON()

    const content = fs.readFileSync(pagesJsonPath, 'utf-8')

    // Both entries must survive the merge.
    expect(content).toContain('pages/h5-only')
    expect(content).toContain('h5 only')
    expect(content).toContain('pages/index')

    // The platform counts tie ('H5' vs 'H5 || MP-WEIXIN'), and the
    // deterministic tie-break keeps the alphabetically last maximum, so the
    // merged pages/index entry is the default platform and stays plain while
    // the H5-only entry is wrapped in an #ifdef block. Check positional
    // attachment, not just presence: pages/index must come before the ifdef
    // block, which must wrap pages/h5-only.
    const indexPos = content.indexOf('"pages/index"')
    const ifdefPos = content.indexOf('#ifdef H5')
    const h5Pos = content.indexOf('"pages/h5-only"')
    const endifPos = content.indexOf('#endif')
    expect(indexPos).toBeGreaterThan(-1)
    expect(indexPos).toBeLessThan(ifdefPos)
    expect(ifdefPos).toBeLessThan(h5Pos)
    expect(h5Pos).toBeLessThan(endifPos)

    // Output must stay parseable as JSON-with-comments.
    const parsed = cjParse(content) as CommentObject
    const pages = parsed.pages
    expect(Array.isArray(pages)).toBe(true)
    if (!Array.isArray(pages)) {
      return
    }
    const paths = pages
      .filter((p): p is CommentObject => typeof p === 'object' && p !== null)
      .map(p => p.path)
    expect(paths).toContain('pages/index')
    expect(paths).toContain('pages/h5-only')
  })
})
