import type { CommentObject } from 'comment-json'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parse as cjParse } from 'comment-json'
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { PageContext } from '../packages/core/src'

/**
 * writePagesJson 中陈旧子包收敛的回归覆盖。
 *
 * 修复前，本次运行扫描不到的子包（每个页面都通过 definePage(null)
 * 退出，或目录被删除）会永远冻结在 pages.json 里：合并循环只更新与
 * 扫描匹配的 root，而读-改-写刻意保留未匹配条目以保护手写内容。
 *
 * 修复让插件生成的子包像主包一样收敛：pages 数组携带生成标记的未
 * 匹配 root 被整个丢弃——当前平台在其中已无可见页面，保留 root
 * （即使其他平台的条目保持包裹）会把一个空子包送进本平台的构建
 * 产物，其 root 目录在磁盘上甚至不存在。丢弃不丢状态：每个平台
 * 每次运行都重写自己扫描的条目，其他平台下次写入时会把 root 加
 * 回来。手写的子包不携带标记，原样保留。
 *
 * 平台模型与 pages-json-home-reorder.test.ts 一致：当前平台通过
 * PageContext 构造函数注入，预置文件代表其他平台的输出。
 */

function writePage(pagesDir: string, name: string, macro: string): void {
  fs.writeFileSync(
    path.join(pagesDir, `${name}.vue`),
    [
      '<script lang="ts" setup>',
      macro,
      '</script>',
      '',
      `<template><div>${name}</div></template>`,
      '',
    ].join('\n'),
    'utf-8',
  )
}

describe('pages.json converges stale plugin-generated sub-packages', () => {
  let tmpDir: string
  let pagesJsonPath: string

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-subpkg-converge-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages')
    fs.mkdirSync(pagesDir, { recursive: true })

    writePage(pagesDir, 'index', 'definePage({ style: { navigationBarTitleText: \'home\' } });')

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')
  })

  beforeEach(() => {
    // 按其他平台此前运行的输出预置子包，一份文件覆盖所有删除几何。
    // 当前平台（mp-weixin）在这里扫描不到任何子包，因此每个插件生成
    // 的 root 对它都是零可见页面、都必须删除——包括多平台的那些，
    // 它们幸存的条目否则会作为空子包外壳进入本平台的构建产物：
    // - pkg-gen-weixin（下标 0，最前位置）：只为 MP-WEIXIN 生成；必须
    //   删除，且它 `}` 与 `,` 之间的用户注释（after-value 注释）不得
    //   泄漏到移入其槽位的条目上
    // - pkg-gen-zero2（下标 1）：同样仅 MP-WEIXIN，与上面相邻，
    //   让删除检验连续两次 splice
    // - pkg-gen-mixed：插件生成，一个 H5 条目 + 一个仅 APP 条目；其他
    //   平台在这里仍有页面，但当前平台的视图为空，root 同样删除
    //   （H5/APP 下次写入时把它加回来）
    // - pkg-gen-strip：为 H5 || MP-WEIXIN 生成；同样的零可见删除，
    //   附带的 plugins 属性随 root 一起消失
    // - pkg-user：手写（无生成标记），有自己的注释；在周围所有生成
    //   条目被 splice 掉之后必须连同注释挂载逐字节幸存
    // - pkg-gen-tail（最后位置）：仅 MP-WEIXIN；必须删除
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    {',
        '      "path": "pages/index",',
        '      "style": {',
        '        "navigationBarTitleText": "home"',
        '      }',
        '    }',
        '  ],',
        '  "subPackages": [',
        '    {',
        '      "root": "pkg-gen-weixin",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
        '        {',
        '          "path": "w1",',
        '          "style": {',
        '            "navigationBarTitleText": "w1"',
        '          }',
        '        }',
        '      ]',
        '    } /* stale note */,',
        '    {',
        '      "root": "pkg-gen-zero2",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
        '        {',
        '          "path": "z1",',
        '          "style": {',
        '            "navigationBarTitleText": "z1"',
        '          }',
        '        }',
        '      ]',
        '    },',
        '    {',
        '      "root": "pkg-gen-mixed",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '        {',
        '          "path": "p1",',
        '          "style": {',
        '            "navigationBarTitleText": "p1"',
        '          }',
        '        },',
        '        // #ifdef APP',
        '        {',
        '          "path": "p2",',
        '          "style": {',
        '            "navigationBarTitleText": "p2"',
        '          }',
        '        }',
        '        // #endif',
        '      ]',
        '    },',
        '    {',
        '      "root": "pkg-gen-strip",',
        '      "plugins": ["test-plugin"],',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN',
        '        {',
        '          "path": "p3",',
        '          "style": {',
        '            "navigationBarTitleText": "p3"',
        '          }',
        '        },',
        '        // #ifdef MP-WEIXIN',
        '        {',
        '          "path": "p4",',
        '          "style": {',
        '            "navigationBarTitleText": "p4"',
        '          }',
        '        }',
        '        // #endif',
        '      ]',
        '    },',
        '    // user maintained package',
        '    {',
        '      "root": "pkg-user",',
        '      "pages": [',
        '        {',
        '          "path": "u1",',
        '          "style": {',
        '            "navigationBarTitleText": "u1"',
        '          }',
        '        }',
        '      ]',
        '    },',
        '    {',
        '      "root": "pkg-gen-tail",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
        '        {',
        '          "path": "t1",',
        '          "style": {',
        '            "navigationBarTitleText": "t1"',
        '          }',
        '        }',
        '      ]',
        '    }',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  const run = async (): Promise<string> => {
    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()
    return fs.readFileSync(pagesJsonPath, 'utf-8')
  }

  it('removes every generated root invisible to the current platform and never touches handwritten packages', async () => {
    const content = await run()

    // 被删除的 root：最前位置、相邻的中间位置、多平台中间条目与最后
    // 位置——它们都没有 MP-WEIXIN 可见的页面，全部整个收敛消失
    expect(content).not.toContain('"pkg-gen-weixin"')
    expect(content).not.toContain('"w1"')
    expect(content).not.toContain('"pkg-gen-zero2"')
    expect(content).not.toContain('"z1"')
    expect(content).not.toContain('"pkg-gen-mixed"')
    expect(content).not.toContain('"p1"')
    expect(content).not.toContain('"p2"')
    expect(content).not.toContain('"pkg-gen-strip"')
    expect(content).not.toContain('"p3"')
    expect(content).not.toContain('"p4"')
    // pkg-gen-strip 上预置的 plugins 属性随 root 一起消失
    expect(content).not.toContain('"test-plugin"')
    expect(content).not.toContain('"pkg-gen-tail"')
    expect(content).not.toContain('"t1"')
    // 被删除首条目的 after-value 注释不得泄漏到移入其槽位的条目上
    expect(content).not.toContain('stale note')

    // pkg-user 不携带生成标记，保持原样；尽管周围所有生成的子包都被
    // splice 掉，它的注释仍直接挂在它的上方
    expect(content).toContain('"u1"')
    const commentPos = content.indexOf('// user maintained package')
    const userPos = content.indexOf('"pkg-user"')
    expect(commentPos).toBeGreaterThan(-1)
    expect(commentPos).toBeLessThan(userPos)

    // 输出仍可解析，且恰好只有手写的 root 幸存
    const parsed = cjParse(content) as CommentObject
    const subPackages = parsed.subPackages
    expect(Array.isArray(subPackages)).toBe(true)
    if (!Array.isArray(subPackages)) {
      return
    }
    const roots = subPackages
      .filter((p): p is CommentObject => typeof p === 'object' && p !== null)
      .map(p => p.root)
    expect(roots).toEqual(['pkg-user'])
  })

  it('keeps the output stable across consecutive runs', async () => {
    const first = await run()
    const second = await run()
    expect(second).toBe(first)
  })
})

describe('pipeline: skipped sub-package pages converge per platform', () => {
  // 下面的用例构成共享同一个 tmpDir 的顺序跨平台时间线：每次运行都
  // 建立在上一次写入的 pages.json 之上。
  let tmpDir: string
  let pkgDir: string
  let pagesJsonPath: string

  const options = {
    dir: 'src/pages',
    outDir: 'src',
    homePage: 'pages/index',
    subPackages: ['src/pkg'],
    dts: false,
  }

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-subpkg-pipeline-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages')
    pkgDir = path.join(tmpDir, 'src', 'pkg')
    fs.mkdirSync(pagesDir, { recursive: true })
    fs.mkdirSync(pkgDir, { recursive: true })

    writePage(pagesDir, 'index', 'definePage({ style: { navigationBarTitleText: \'home\' } });')
    writePage(
      pkgDir,
      'alipay-only',
      'definePage(({ platform }) => (platform === \'mp-weixin\' ? null : { style: { navigationBarTitleText: \'alipay only\' } }));',
    )

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  const run = async (platform: string): Promise<CommentObject> => {
    const ctx = new PageContext(options, tmpDir, platform)
    await ctx.updatePagesJSON()
    return cjParse(fs.readFileSync(pagesJsonPath, 'utf-8')) as CommentObject
  }

  const subRoots = (parsed: CommentObject): unknown[] =>
    Array.isArray(parsed.subPackages) ? parsed.subPackages : []

  it('writes the sub-package on platforms where the page exists', async () => {
    const parsed = await run('mp-alipay')
    const roots = subRoots(parsed)
    expect(roots.length).toBe(1)
    const pages = (roots[0] as CommentObject).pages
    expect(Array.isArray(pages)).toBe(true)
    if (!Array.isArray(pages)) {
      return
    }
    expect(pages.map(p => (p as CommentObject).path)).toEqual(['alipay-only'])
  })

  it('drops the root when the page is skipped on the current platform', async () => {
    const parsed = await run('mp-weixin')
    // 页面在 mp-weixin 上被跳过，子包因此没有该平台可见的页面。
    // root 必须整个删除：保留它（即使 MP-ALIPAY 条目包在 #ifdef 里）
    // 会给微信构建送出一个产物中不存在其 root 目录的空子包。删除不
    // 丢状态——mp-alipay 会从自己的扫描重写 root（见下一用例）
    expect(Array.isArray(parsed.subPackages)).toBe(true)
    expect(subRoots(parsed).length).toBe(0)
    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    expect(content).not.toContain('"alipay-only"')
    // 主包原样幸存
    expect(content).toContain('"pages/index"')
  })

  it('re-adds the root on the next write of a platform that still has pages', async () => {
    const parsed = await run('mp-alipay')
    // 扫描再次产出该页面，root 以单平台标记下的裸形式回来——证明
    // 之前的删除没有丢状态
    const roots = subRoots(parsed)
    expect(roots.length).toBe(1)
    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    expect(content).toContain('GENERATED BY UNI-PAGES, PLATFORM: MP-ALIPAY\n')
    expect(content).toContain('"alipay-only"')
    expect(content).not.toContain('#ifdef')
  })

  it('removes the root once no platform produces pages for it anymore', async () => {
    // 删除页面文件后再跑一次 mp-alipay：扫描不到 root，
    // 收敛把它移除
    fs.rmSync(path.join(pkgDir, 'alipay-only.vue'))

    const parsed = await run('mp-alipay')
    // 防止回归把 subPackages 键整个删掉——
    // 只检查空数组长度捕捉不到这种问题
    expect(Array.isArray(parsed.subPackages)).toBe(true)
    expect(subRoots(parsed).length).toBe(0)
    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    expect(content).not.toContain('"alipay-only"')

    // 主包在子包删除后原样幸存
    expect(content).toContain('"pages/index"')
  })
})

describe('pipeline: a sub-package empty on the current platform stays out of its view', () => {
  // PR #286 评审问题的回归：子包的页面只存在于 H5，且在 MP-WEIXIN 上
  // 全部通过 definePage(null) 退出。resolvePlatformUnion 过去只从仍然
  // 存在的条目收集平台，微信运行零贡献后全集停留在 'H5'，仅 H5 的
  // 条目被判定为覆盖全集而裸露输出——泄漏进微信的条件编译视图（裸
  // 条目对所有平台可见）。当前平台必须始终加入全集。在此基础上，
  // 对当前平台没有剩余页面的插件生成子包被整个丢弃：微信构建产物
  // 中没有对应的目录，app.json 条目（即使其页面全被包裹掉）会指向
  // 不存在的东西。
  let tmpDir: string
  let pagesJsonPath: string

  const options = {
    dir: 'src/pages',
    outDir: 'src',
    homePage: 'pages/index',
    subPackages: ['src/pkg'],
    dts: false,
  }

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-subpkg-empty-platform-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages')
    const pkgDir = path.join(tmpDir, 'src', 'pkg')
    fs.mkdirSync(pagesDir, { recursive: true })
    fs.mkdirSync(pkgDir, { recursive: true })

    writePage(pagesDir, 'index', 'definePage({ style: { navigationBarTitleText: \'home\' } });')
    writePage(
      pkgDir,
      'h5-only',
      'definePage(({ platform }) => (platform === \'mp-weixin\' ? null : { style: { navigationBarTitleText: \'h5 only\' } }));',
    )

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  const run = async (platform: string): Promise<string> => {
    const ctx = new PageContext(options, tmpDir, platform)
    await ctx.updatePagesJSON()
    return fs.readFileSync(pagesJsonPath, 'utf-8')
  }

  it('emits the sub-package bare while its only platform is the current one', async () => {
    const content = await run('h5')
    const segment = content.slice(content.indexOf('"pkg"'))
    expect(segment).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5\n')
    expect(segment).toContain('"h5-only"')
    expect(segment).not.toContain('#ifdef')
  })

  it('drops the sub-package entirely on the zero-contribution platform', async () => {
    const content = await run('mp-weixin')

    // 该子包没有任何 MP-WEIXIN 可见的页面，root 不得以任何形式幸存
    // ——残留的 root（裸露或全部包裹）都会给微信构建送出一个产物中
    // 不存在其 root 目录的空子包
    expect(content).not.toContain('"pkg"')
    expect(content).not.toContain('"h5-only"')
    // 主包原样幸存
    expect(content).toContain('"pages/index"')
    // 防止空转通过：subPackages 必须仍序列化为（空的）数组，
    // 而不是从输出中消失
    const parsed = cjParse(content) as CommentObject
    expect(Array.isArray(parsed.subPackages)).toBe(true)
  })

  it('stays byte-stable across consecutive zero-contribution runs', async () => {
    const first = fs.readFileSync(pagesJsonPath, 'utf-8')
    const second = await run('mp-weixin')
    expect(second).toBe(first)
  })

  it('re-adds the sub-package once its own platform re-runs', async () => {
    // H5 运行重新扫描该页面并把 root 裸露地写回——之前的删除没有
    // 丢状态
    const content = await run('h5')
    const segment = content.slice(content.indexOf('"pkg"'))
    expect(segment).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5\n')
    expect(segment).toContain('"h5-only"')
    expect(segment).not.toContain('#ifdef')
  })
})
