import type { CommentObject } from 'comment-json'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parse as cjParse } from 'comment-json'
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { PageContext } from '../packages/core/src'

/**
 * comment-json v5 空行处理的回归覆盖。
 *
 * comment-json v5 在解析到的 JSON 含空行时会输出 `BlankLine` 令牌
 * （不带 `value` 属性）——手工格式化的 pages.json 正是这种样子。
 * `mergePlatformItems` 过去假设 `before:N` 注释数组中的每个令牌都带
 * `value`，于是以 `Cannot read properties of undefined (reading
 * 'trim')` 崩溃。
 *
 * 平台模型与 concurrent-pages-json.test.ts 一致：当前平台
 * （mp-weixin）通过 PageContext 构造函数注入，预置文件代表另一个
 * 终端（H5）的输出。
 */

describe('pages.json with blank lines (comment-json v5 BlankLine tokens)', () => {
  let tmpDir: string
  let srcDir: string
  let pagesJsonPath: string

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-blank-lines-'))
    srcDir = path.join(tmpDir, 'src')
    const pagesDir = path.join(srcDir, 'pages')
    fs.mkdirSync(pagesDir, { recursive: true })

    fs.writeFileSync(
      path.join(pagesDir, 'index.vue'),
      [
        '<script lang="ts" setup>',
        'definePage(() => ({ style: { navigationBarTitleText: \'home\' } }));',
        '</script>',
        '',
        '<template><div>home</div></template>',
        '',
      ].join('\n'),
      'utf-8',
    )

    pagesJsonPath = path.join(srcDir, 'pages.json')
  })

  beforeEach(() => {
    // 预置一份手工格式化的 pages.json：生成标记周围、条件编译注释
    // 周围以及条目之间都有空行。每个空行都会变成某个 `before:N`
    // 数组中的 BlankLine 令牌。
    //
    // 预置的 `pages/index` 条目与扫描到的页面解析结果一致，因此合并
    // 成单个条目并保持在结果首位。这让测试专注于空行处理；
    // writePagesJson 中的首页重排由 pages-json-home-reorder.test.ts
    // 单独覆盖。
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '',
        '    {',
        '      "path": "pages/index",',
        '      "style": {',
        '        "navigationBarTitleText": "home"',
        '      }',
        '    },',
        '',
        '    // #ifdef H5',
        '    {',
        '      "path": "pages/h5-only",',
        '      "style": {',
        '        "navigationBarTitleText": "h5 only"',
        '      }',
        '    }',
        '    // #endif',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it('merges without crashing and keeps other platforms\' entries', async () => {
    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    // 加入 BlankLine 守卫之前，这里会在 mergePlatformItems 内部抛错。
    await ctx.updatePagesJSON()

    const content = fs.readFileSync(pagesJsonPath, 'utf-8')

    // 两个条目都得在合并后留下来。
    expect(content).toContain('pages/h5-only')
    expect(content).toContain('h5 only')
    expect(content).toContain('pages/index')

    // 合并后的 pages/index 条目盖住了全部平台（'H5 || MP-WEIXIN'），
    // 不用包 #ifdef；只有 H5 的条目包着 #ifdef 块。要比位置、不能
    // 只比有没有：pages/index 必须在 ifdef 块之前，ifdef 块必须包住
    // pages/h5-only。
    const indexPos = content.indexOf('"pages/index"')
    const ifdefPos = content.indexOf('#ifdef H5\n')
    const h5Pos = content.indexOf('"pages/h5-only"')
    const endifPos = content.indexOf('#endif', h5Pos)
    expect(indexPos).toBeGreaterThan(-1)
    expect(indexPos).toBeLessThan(ifdefPos)
    expect(ifdefPos).toBeLessThan(h5Pos)
    expect(h5Pos).toBeLessThan(endifPos)

    // 输出必须仍可按带注释的 JSON 解析。
    const parsed = cjParse(content) as CommentObject
    const pages = parsed.pages
    expect(Array.isArray(pages)).toBe(true)
    if (!Array.isArray(pages)) {
      return
    }
    const paths = pages
      .filter((p): p is CommentObject => typeof p === 'object' && p !== null)
      .map(p => p.path)
    expect(paths).toContain('pages/index')
    expect(paths).toContain('pages/h5-only')
  })
})
