import type { CommentObject } from 'comment-json'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parse as cjParse } from 'comment-json'
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { PageContext } from '../packages/core/src'

/**
 * writePagesJson 中过期子包被清掉的回归测试。
 *
 * 修复前，本次运行扫描不到的子包（每个页面都通过 definePage(null)
 * 退出，或目录被删除）会永远冻在 pages.json 里：合并循环只更新和
 * 扫描结果匹配的 root，而读-改-写故意保留没匹配上的条目，为的是
 * 保护手写内容。
 *
 * 修复让插件生成的子包和主包一样能自动清掉：pages 数组带生成标记
 * 的、没匹配上的 root 被整个丢弃——当前平台在里面已经没有看得见的
 * 页面，留着 root（哪怕其他平台的条目都包着 #ifdef）会往本平台的
 * 构建产物里塞一个空子包，它的 root 目录在磁盘上甚至不存在。丢弃
 * 不丢状态：每个平台每次运行都重写自己扫描到的条目，其他平台下次
 * 写入时会把 root 加回来。手写的子包不带标记，原样保留。
 *
 * 平台模型和 pages-json-home-reorder.test.ts 一样：当前平台从
 * PageContext 构造函数传进去，预置文件代表其他平台的输出。
 */

function writePage(pagesDir: string, name: string, macro: string): void {
  fs.writeFileSync(
    path.join(pagesDir, `${name}.vue`),
    [
      '<script lang="ts" setup>',
      macro,
      '</script>',
      '',
      `<template><div>${name}</div></template>`,
      '',
    ].join('\n'),
    'utf-8',
  )
}

describe('pages.json converges stale plugin-generated sub-packages', () => {
  let tmpDir: string
  let pagesJsonPath: string

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-subpkg-converge-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages')
    fs.mkdirSync(pagesDir, { recursive: true })

    writePage(pagesDir, 'index', 'definePage({ style: { navigationBarTitleText: \'home\' } });')

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')
  })

  beforeEach(() => {
    // 按其他平台此前运行的输出预置子包，一份文件覆盖所有删除位置的
    // 组合。当前平台（mp-weixin）在这里扫描不到任何子包，所以每个
    // 插件生成的 root 对它都没有可见页面、都得删——包括多平台的那些，
    // 它们留下的条目否则会作为空壳子包进入本平台的构建产物：
    // - pkg-gen-weixin（下标 0，最前面的位置）：只为 MP-WEIXIN 生成；
    //   必须删除，而且它 `}` 与 `,` 之间的用户注释（after-value 注释）
    //   不能漏到挪进这个位置的条目身上
    // - pkg-gen-zero2（下标 1）：同样只有 MP-WEIXIN，和上面相邻，
    //   检验连续两次删除
    // - pkg-gen-mixed：插件生成，一个 H5 条目 + 一个仅 APP 条目；其他
    //   平台在这里还有页面，但当前平台一个也看不见，root 同样删
    //   （H5/APP 下次写入时会把它加回来）
    // - pkg-gen-strip：为 H5 || MP-WEIXIN 生成；同样删掉，
    //   附带的 plugins 属性跟着 root 一起消失
    // - pkg-user：手写（没有生成标记），有自己的注释；周围生成的
    //   子包全被删掉之后，它必须连同注释一个字节不动地留下
    // - pkg-gen-tail（最后的位置）：仅 MP-WEIXIN；必须删除
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    {',
        '      "path": "pages/index",',
        '      "style": {',
        '        "navigationBarTitleText": "home"',
        '      }',
        '    }',
        '  ],',
        '  "subPackages": [',
        '    {',
        '      "root": "pkg-gen-weixin",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
        '        {',
        '          "path": "w1",',
        '          "style": {',
        '            "navigationBarTitleText": "w1"',
        '          }',
        '        }',
        '      ]',
        '    } /* stale note */,',
        '    {',
        '      "root": "pkg-gen-zero2",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
        '        {',
        '          "path": "z1",',
        '          "style": {',
        '            "navigationBarTitleText": "z1"',
        '          }',
        '        }',
        '      ]',
        '    },',
        '    {',
        '      "root": "pkg-gen-mixed",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '        {',
        '          "path": "p1",',
        '          "style": {',
        '            "navigationBarTitleText": "p1"',
        '          }',
        '        },',
        '        // #ifdef APP',
        '        {',
        '          "path": "p2",',
        '          "style": {',
        '            "navigationBarTitleText": "p2"',
        '          }',
        '        }',
        '        // #endif',
        '      ]',
        '    },',
        '    {',
        '      "root": "pkg-gen-strip",',
        '      "plugins": ["test-plugin"],',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN',
        '        {',
        '          "path": "p3",',
        '          "style": {',
        '            "navigationBarTitleText": "p3"',
        '          }',
        '        },',
        '        // #ifdef MP-WEIXIN',
        '        {',
        '          "path": "p4",',
        '          "style": {',
        '            "navigationBarTitleText": "p4"',
        '          }',
        '        }',
        '        // #endif',
        '      ]',
        '    },',
        '    // user maintained package',
        '    {',
        '      "root": "pkg-user",',
        '      "pages": [',
        '        {',
        '          "path": "u1",',
        '          "style": {',
        '            "navigationBarTitleText": "u1"',
        '          }',
        '        }',
        '      ]',
        '    },',
        '    {',
        '      "root": "pkg-gen-tail",',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
        '        {',
        '          "path": "t1",',
        '          "style": {',
        '            "navigationBarTitleText": "t1"',
        '          }',
        '        }',
        '      ]',
        '    }',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  const run = async (): Promise<string> => {
    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index', dts: false },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()
    return fs.readFileSync(pagesJsonPath, 'utf-8')
  }

  it('removes every generated root invisible to the current platform and never touches handwritten packages', async () => {
    const content = await run()

    // 被删除的 root：最前面的位置、相邻的中间位置、多平台的中间条目
    // 和最后的位置——它们都没有 MP-WEIXIN 看得见的页面，全部整个消失
    expect(content).not.toContain('"pkg-gen-weixin"')
    expect(content).not.toContain('"w1"')
    expect(content).not.toContain('"pkg-gen-zero2"')
    expect(content).not.toContain('"z1"')
    expect(content).not.toContain('"pkg-gen-mixed"')
    expect(content).not.toContain('"p1"')
    expect(content).not.toContain('"p2"')
    expect(content).not.toContain('"pkg-gen-strip"')
    expect(content).not.toContain('"p3"')
    expect(content).not.toContain('"p4"')
    // pkg-gen-strip 上预置的 plugins 属性随 root 一起消失
    expect(content).not.toContain('"test-plugin"')
    expect(content).not.toContain('"pkg-gen-tail"')
    expect(content).not.toContain('"t1"')
    // 被删掉的首条目身上 after-value 位置的注释，不能漏到挪进这个
    // 位置的条目身上
    expect(content).not.toContain('stale note')

    // pkg-user 没有生成标记，保持原样；周围生成的子包全被删掉，
    // 它的注释还挂在它正上方
    expect(content).toContain('"u1"')
    const commentPos = content.indexOf('// user maintained package')
    const userPos = content.indexOf('"pkg-user"')
    expect(commentPos).toBeGreaterThan(-1)
    expect(commentPos).toBeLessThan(userPos)

    // 输出仍可解析，而且只剩手写的 root
    const parsed = cjParse(content) as CommentObject
    const subPackages = parsed.subPackages
    expect(Array.isArray(subPackages)).toBe(true)
    if (!Array.isArray(subPackages)) {
      return
    }
    const roots = subPackages
      .filter((p): p is CommentObject => typeof p === 'object' && p !== null)
      .map(p => p.root)
    expect(roots).toEqual(['pkg-user'])
  })

  it('keeps the output stable across consecutive runs', async () => {
    const first = await run()
    const second = await run()
    expect(second).toBe(first)
  })
})

describe('pipeline: skipped sub-package pages converge per platform', () => {
  // 下面的用例构成共享同一个 tmpDir 的顺序跨平台时间线：每次运行都
  // 建立在上一次写入的 pages.json 之上。
  let tmpDir: string
  let pkgDir: string
  let pagesJsonPath: string

  const options = {
    dir: 'src/pages',
    outDir: 'src',
    homePage: 'pages/index',
    subPackages: ['src/pkg'],
    dts: false,
  }

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-subpkg-pipeline-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages')
    pkgDir = path.join(tmpDir, 'src', 'pkg')
    fs.mkdirSync(pagesDir, { recursive: true })
    fs.mkdirSync(pkgDir, { recursive: true })

    writePage(pagesDir, 'index', 'definePage({ style: { navigationBarTitleText: \'home\' } });')
    writePage(
      pkgDir,
      'alipay-only',
      'definePage(({ platform }) => (platform === \'mp-weixin\' ? null : { style: { navigationBarTitleText: \'alipay only\' } }));',
    )

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  const run = async (platform: string): Promise<CommentObject> => {
    const ctx = new PageContext(options, tmpDir, platform)
    await ctx.updatePagesJSON()
    return cjParse(fs.readFileSync(pagesJsonPath, 'utf-8')) as CommentObject
  }

  const subRoots = (parsed: CommentObject): unknown[] =>
    Array.isArray(parsed.subPackages) ? parsed.subPackages : []

  it('writes the sub-package on platforms where the page exists', async () => {
    const parsed = await run('mp-alipay')
    const roots = subRoots(parsed)
    expect(roots.length).toBe(1)
    const pages = (roots[0] as CommentObject).pages
    expect(Array.isArray(pages)).toBe(true)
    if (!Array.isArray(pages)) {
      return
    }
    expect(pages.map(p => (p as CommentObject).path)).toEqual(['alipay-only'])
  })

  it('drops the root when the page is skipped on the current platform', async () => {
    const parsed = await run('mp-weixin')
    // 页面在 mp-weixin 上被跳过，子包就没有该平台看得见的页面。root
    // 必须整个删掉：留着它（哪怕 MP-ALIPAY 条目包在 #ifdef 里）会往
    // 微信构建产物里塞一个空子包，产物里根本没有它的 root 目录。删掉
    // 不丢状态——mp-alipay 会用自己的扫描把 root 写回来（见下一用例）
    expect(Array.isArray(parsed.subPackages)).toBe(true)
    expect(subRoots(parsed).length).toBe(0)
    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    expect(content).not.toContain('"alipay-only"')
    // 主包原样留下
    expect(content).toContain('"pages/index"')
  })

  it('re-adds the root on the next write of a platform that still has pages', async () => {
    const parsed = await run('mp-alipay')
    // 扫描再次找到该页面，root 不带 #ifdef 地写回来（生成标记里只有
    // MP-ALIPAY 一个平台）——证明之前的删除没丢状态
    const roots = subRoots(parsed)
    expect(roots.length).toBe(1)
    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    expect(content).toContain('GENERATED BY UNI-PAGES, PLATFORM: MP-ALIPAY\n')
    expect(content).toContain('"alipay-only"')
    expect(content).not.toContain('#ifdef')
  })

  it('removes the root once no platform produces pages for it anymore', async () => {
    // 删掉页面文件再跑一次 mp-alipay：扫描不到 root，这回把它移除
    fs.rmSync(path.join(pkgDir, 'alipay-only.vue'))

    const parsed = await run('mp-alipay')
    // 防止回归把 subPackages 键整个删掉——
    // 只检查空数组长度捕捉不到这种问题
    expect(Array.isArray(parsed.subPackages)).toBe(true)
    expect(subRoots(parsed).length).toBe(0)
    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    expect(content).not.toContain('"alipay-only"')

    // 主包在子包删除后原样留下
    expect(content).toContain('"pages/index"')
  })
})

describe('pipeline: a sub-package empty on the current platform stays out of its view', () => {
  // PR #286 评审问题的回归：子包的页面只存在于 H5，而且在 MP-WEIXIN
  // 上全都通过 definePage(null) 退出。resolvePlatformUnion 以前只从
  // 还在的条目收集平台，微信运行什么都没贡献后全集只剩 'H5'，只有
  // H5 的条目被误认为盖住了全集、不加包裹输出——漏进微信的构建结果
  // （不包着的条目所有平台都看得见）。当前平台必须始终进全集。在此
  // 基础上，对当前平台没有剩下页面的插件生成子包被整个丢掉：微信
  // 构建产物里没有对应的目录，app.json 条目（哪怕它的页面全被包掉）
  // 会指向不存在的东西。
  let tmpDir: string
  let pagesJsonPath: string

  const options = {
    dir: 'src/pages',
    outDir: 'src',
    homePage: 'pages/index',
    subPackages: ['src/pkg'],
    dts: false,
  }

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-subpkg-empty-platform-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages')
    const pkgDir = path.join(tmpDir, 'src', 'pkg')
    fs.mkdirSync(pagesDir, { recursive: true })
    fs.mkdirSync(pkgDir, { recursive: true })

    writePage(pagesDir, 'index', 'definePage({ style: { navigationBarTitleText: \'home\' } });')
    writePage(
      pkgDir,
      'h5-only',
      'definePage(({ platform }) => (platform === \'mp-weixin\' ? null : { style: { navigationBarTitleText: \'h5 only\' } }));',
    )

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  const run = async (platform: string): Promise<string> => {
    const ctx = new PageContext(options, tmpDir, platform)
    await ctx.updatePagesJSON()
    return fs.readFileSync(pagesJsonPath, 'utf-8')
  }

  it('emits the sub-package bare while its only platform is the current one', async () => {
    const content = await run('h5')
    const segment = content.slice(content.indexOf('"pkg"'))
    expect(segment).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5\n')
    expect(segment).toContain('"h5-only"')
    expect(segment).not.toContain('#ifdef')
  })

  it('drops the sub-package entirely on the zero-contribution platform', async () => {
    const content = await run('mp-weixin')

    // 该子包没有任何 MP-WEIXIN 看得见的页面，root 不能以任何形式
    // 留下——留下的 root（不包着或全包着）都会往微信构建产物里塞
    // 一个产物里不存在其 root 目录的空子包
    expect(content).not.toContain('"pkg"')
    expect(content).not.toContain('"h5-only"')
    // 主包原样留下
    expect(content).toContain('"pages/index"')
    // 防止空转也通过：subPackages 必须仍然输出成一个（空的）数组，
    // 不能整个消失
    const parsed = cjParse(content) as CommentObject
    expect(Array.isArray(parsed.subPackages)).toBe(true)
  })

  it('stays byte-stable across consecutive zero-contribution runs', async () => {
    const first = fs.readFileSync(pagesJsonPath, 'utf-8')
    const second = await run('mp-weixin')
    expect(second).toBe(first)
  })

  it('re-adds the sub-package once its own platform re-runs', async () => {
    // H5 运行重新扫描该页面，把 root 不带 #ifdef 地写回来——之前的
    // 删除没丢状态
    const content = await run('h5')
    const segment = content.slice(content.indexOf('"pkg"'))
    expect(segment).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5\n')
    expect(segment).toContain('"h5-only"')
    expect(segment).not.toContain('#ifdef')
  })
})

describe('pipeline: sub-package plugins follow the config', () => {
  // plugins 残留的回归：合并循环只在配置里有 plugins 时赋值，配置里
  // 删掉后什么都不做，写进 pages.json 的 plugins 就永远留下——用户
  // 从 subPackages 配置里移除一个插件，产物里的分包插件却下不去。
  // 修复后插件生成的子包（pages 带生成标记）跟随配置清理；手写的
  // 子包没有标记，plugins 原样保留。
  let tmpDir: string
  let pagesJsonPath: string
  let configPath: string

  const options = {
    dir: 'src/pages',
    outDir: 'src',
    homePage: 'pages/index',
    subPackages: ['src/pkg'],
    dts: false,
  }

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-subpkg-plugins-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages')
    const pkgDir = path.join(tmpDir, 'src', 'pkg')
    fs.mkdirSync(pagesDir, { recursive: true })
    fs.mkdirSync(pkgDir, { recursive: true })

    writePage(pagesDir, 'index', 'definePage({ style: { navigationBarTitleText: \'home\' } });')
    writePage(pkgDir, 'p1', 'definePage({ style: { navigationBarTitleText: \'p1\' } });')

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')
    configPath = path.join(tmpDir, 'pages.config.json')
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  const writeConfig = (subPackages: unknown[]): void => {
    fs.writeFileSync(configPath, JSON.stringify({ subPackages }), 'utf-8')
  }

  const run = async (): Promise<string> => {
    const ctx = new PageContext(options, tmpDir, 'h5')
    await ctx.updatePagesJSON()
    return fs.readFileSync(pagesJsonPath, 'utf-8')
  }

  it('removes plugins from generated packages once the config drops them', async () => {
    // 第一次运行：配置带 plugins，随生成的子包写进 pages.json
    writeConfig([{ root: 'pkg', plugins: ['test-plugin'] }])
    let content = await run()
    expect(content).toContain('"test-plugin"')
    expect(content).toContain('"p1"')

    // 配置删掉 plugins 再跑：子包还在（页面还在扫描结果里），但
    // plugins 不能残留
    writeConfig([{ root: 'pkg' }])
    content = await run()
    expect(content).toContain('"pkg"')
    expect(content).toContain('"p1"')
    expect(content).not.toContain('"test-plugin"')
  })

  it('never strips plugins from a handwritten package without a generation marker', async () => {
    // 预置一个手写子包：root 不在扫描目录里、pages 没有生成标记，
    // 但带着 plugins。它既不会被扫描命中也不在配置里，必须原样保留
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    {',
        '      "path": "pages/index",',
        '      "style": { "navigationBarTitleText": "home" }',
        '    }',
        '  ],',
        '  "subPackages": [',
        '    {',
        '      "root": "pkg",',
        '      "plugins": ["generated-plugin"],',
        '      "pages": [',
        '        // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '        {',
        '          "path": "p1",',
        '          "style": { "navigationBarTitleText": "p1" }',
        '        }',
        '      ]',
        '    },',
        '    {',
        '      "root": "pkg-hand",',
        '      "plugins": ["hand-plugin"],',
        '      "pages": [',
        '        {',
        '          "path": "h1",',
        '          "style": { "navigationBarTitleText": "h1" }',
        '        }',
        '      ]',
        '    }',
        '  ]',
        '}',
      ].join('\n'),
      'utf-8',
    )

    // 配置里没有任何 plugins
    writeConfig([])
    const content = await run()

    // 生成的子包（带标记）没有配置来源的 plugins，被清掉
    expect(content).not.toContain('generated-plugin')
    // 手写子包原样保留，plugins 一个字节不动
    expect(content).toContain('"pkg-hand"')
    expect(content).toContain('"hand-plugin"')
    expect(content).toContain('"h1"')
  })
})
