import type { PagesJsonData } from '../packages/core/src'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { mergePagesJson, PageContext, writePagesJson } from '../packages/core/src'

/**
 * 直接测试 mergePagesJson 这个纯函数。
 *
 * 它输入字符串、输出字符串，中间完成全部计算（多平台 #ifdef 合并、
 * 生成标记、首页排前、子包合并、格式化），所以这些用例直接对比生成
 * 的内容，不用建临时目录，也不用碰 comment-json 的内部符号。
 */

describe('mergePagesJson pure merge seam', () => {
  it('throws a recognizable error when the existing pages.json is malformed', () => {
    // 手写出错的 pages.json（这里少了对象体）以前把 comment-json 的
    // 原始 SyntaxError 直接抛给用户，看不出是哪个文件的问题。现在
    // 错误信息要带上 pages.json 的字样，用户才知道去哪里修
    expect(() => mergePagesJson('{ "pages": [ }', {
      pages: [{ path: 'pages/index/index', type: 'home' }],
      subPackages: [],
    }, { platform: 'h5' })).toThrowError(/Failed to parse the existing pages\.json/)
  })

  it('merges an identical entry across platforms without duplicating it', () => {
    // 模拟旧文件或用户手写文件的样子：生成标记下面只有一个条目，
    // 不带内部 `type` 标记
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
      '    {',
      '      "path": "pages/index/index",',
      '      "style": {',
      '        "navigationBarTitleText": "uni-app"',
      '      }',
      '    }',
      '  ],',
      '  "subPackages": []',
      '}',
      '',
    ].join('\n')

    const content = mergePagesJson(existing, {
      pages: [{
        path: 'pages/index/index',
        type: 'home',
        style: { navigationBarTitleText: 'uni-app' },
      }],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    // 两个平台的条目内容相同，合并成一条，不带 #ifdef 块
    // （issue #283 的回归防护）
    expect(content.match(/pages\/index\/index/g)).toHaveLength(1)
    expect(content).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN')
    expect(content).not.toContain('#ifdef')
    // 合并时保留的是输入文件里原来的对象，所以不会出现 `type` 标记
    expect(content).not.toContain('"type"')
  })

  it('keeps the type marker on freshly generated entries by design', () => {
    // 插件自己写的条目会带着内部 `type` 标记进 pages.json：
    // 之后的运行靠它找回首页
    const content = mergePagesJson('', {
      pages: [{ path: 'pages/index/index', type: 'home' }],
      subPackages: [],
    }, { platform: 'h5' })

    expect(content).toContain('"type": "home"')
  })

  it('keeps diverging entries behind platform #ifdef blocks', () => {
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
      '    {',
      '      "path": "pages/index/index",',
      '      "style": {',
      '        "navigationBarTitleText": "h5 title"',
      '      }',
      '    }',
      '  ],',
      '  "subPackages": []',
      '}',
      '',
    ].join('\n')

    const content = mergePagesJson(existing, {
      pages: [{
        path: 'pages/index/index',
        type: 'home',
        style: { navigationBarTitleText: 'weixin title' },
      }],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    expect(content).toContain('#ifdef H5')
    expect(content).toContain('#ifdef MP-WEIXIN')
    expect(content).toContain('h5 title')
    expect(content).toContain('weixin title')
    // 两个变体都没盖住全部平台（'H5 || MP-WEIXIN'），所以都包着
    // #ifdef：解开任何一个，它都会漏进另一个平台能看到的内容里
    expect(content.match(/#ifdef/g)).toHaveLength(2)
    expect(content.match(/#endif/g)).toHaveLength(2)
    // 每个块包裹的是自己平台的变体，而非对方的
    expect(content.indexOf('#ifdef H5')).toBeLessThan(content.indexOf('h5 title'))
    expect(content.indexOf('#ifdef MP-WEIXIN')).toBeLessThan(content.indexOf('weixin title'))
    // 首页条目按其 type 标记被重排到第一位
    expect(content.indexOf('weixin title')).toBeLessThan(content.indexOf('h5 title'))
  })

  it('moves the home page to the first position by path', () => {
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
      '    {',
      '      "path": "pages/a/a"',
      '    },',
      '    {',
      '      "path": "pages/home/home"',
      '    }',
      '  ],',
      '  "subPackages": []',
      '}',
      '',
    ].join('\n')

    const content = mergePagesJson(existing, {
      pages: [
        { path: 'pages/a/a', type: 'page' },
        { path: 'pages/home/home', type: 'home' },
      ],
      subPackages: [],
      homePath: 'pages/home/home',
    }, { platform: 'h5' })

    expect(content.indexOf('pages/home/home')).toBeLessThan(content.indexOf('pages/a/a'))
    // 生成标记在重排后恰好保留一份，且位于所有页面条目之前
    expect(content.match(/GENERATED BY UNI-PAGES/g)).toHaveLength(1)
    expect(content.indexOf('GENERATED BY UNI-PAGES')).toBeLessThan(content.indexOf('pages/home/home'))
  })

  it('keeps the current platform in the union even when it contributes zero pages', () => {
    // PR #286 评审发现的问题的回归测试：以前平台全集只从剩下的条目
    // 推算，一次什么都没贡献的运行会让全集只剩别的平台，别的平台的
    // 条目被误认为"盖住了全集"而不加包裹输出，漏进本平台的构建结果
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
      '    {',
      '      "path": "pages/h5-only/index",',
      '      "style": {',
      '        "navigationBarTitleText": "h5 only"',
      '      }',
      '    }',
      '  ],',
      '  "subPackages": []',
      '}',
      '',
    ].join('\n')

    const content = mergePagesJson(existing, {
      pages: [],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    // MP-WEIXIN 什么都没贡献也进标记；只有 H5 的条目保持包裹，
    // 不会被误认为盖住了全集而不加包裹输出
    expect(content).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN')
    expect(content).toContain('#ifdef H5')
    expect(content.indexOf('#ifdef H5')).toBeLessThan(content.indexOf('h5 only'))
    expect(content.indexOf('h5 only')).toBeLessThan(content.indexOf('#endif'))
  })

  it('keeps the foreign platform wrapped when its owner re-runs after a zero-contribution run', () => {
    // 防来回跳变的回归：上面那个用例还得扛住 H5 → MP-WEIXIN → H5
    // 连跑三轮。H5 重跑时，原来包在 #ifdef H5 里的条目被新扫描结果
    // 替换（它的平台列表去掉当前平台后空了），"微信来过"这件事只剩
    // 生成标记还记得。所以平台全集必须把标记里的平台也算上——只看
    // 剩下的条目会把 MP-WEIXIN 弄丢，H5 的条目会不加包裹输出、再次
    // 漏进微信的构建结果，直到下一次微信运行重新包上
    const h5Pages = [
      { path: 'pages/h5-only/index', style: { navigationBarTitleText: 'h5 only' } },
    ]

    const step1 = mergePagesJson('', {
      pages: h5Pages,
      subPackages: [],
    }, { platform: 'h5' })
    expect(step1).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5\n')
    expect(step1).not.toContain('#ifdef')

    const step2 = mergePagesJson(step1, {
      pages: [],
      subPackages: [],
    }, { platform: 'mp-weixin' })
    expect(step2).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN')
    expect(step2).toContain('#ifdef H5')

    const step3 = mergePagesJson(step2, {
      pages: h5Pages,
      subPackages: [],
    }, { platform: 'h5' })
    expect(step3).toContain('GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN')
    expect(step3).toContain('#ifdef H5')
    expect(step3.indexOf('#ifdef H5')).toBeLessThan(step3.indexOf('h5 only'))
    expect(step3.indexOf('h5 only')).toBeLessThan(step3.indexOf('#endif'))
  })

  it('converges plugin-generated sub-packages missing from this run', () => {
    const existing = [
      '{',
      '  "pages": [],',
      '  "subPackages": [',
      '    {',
      '      "root": "pages-sub",',
      '      "pages": [',
      '        // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
      '        {',
      '          "path": "pages/index"',
      '        }',
      '      ]',
      '    },',
      '    {',
      '      "root": "user-sub",',
      '      "pages": [',
      '        {',
      '          "path": "pages/keep"',
      '        }',
      '      ]',
      '    }',
      '  ]',
      '}',
      '',
    ].join('\n')

    // 本次运行在 mp-weixin 上扫描不到任何子包：插件生成的子包
    // （只属于当前平台）整个消失，手写的子包原样保留
    const content = mergePagesJson(existing, {
      pages: [],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    expect(content).not.toContain('pages-sub')
    expect(content).toContain('user-sub')
    expect(content).toContain('pages/keep')
  })

  it('applies the serialization format options', () => {
    const data = {
      pages: [{ path: 'pages/index/index', type: 'home' as const }],
      subPackages: [],
    }

    const minified = mergePagesJson('', data, { platform: 'h5', format: { minify: true } })
    expect(minified).not.toContain('\n')
    // 单行 JSON 无法携带注释：生成标记被丢弃，
    // 多平台跟踪在下次运行从头开始
    expect(minified).not.toContain('GENERATED BY UNI-PAGES')

    const tabbed = mergePagesJson('', data, { platform: 'h5', format: { indent: '\t', insertFinalNewline: true } })
    expect(tabbed).toContain('\t')
    expect(tabbed.endsWith('\n')).toBe(true)

    const crlf = mergePagesJson('', data, { platform: 'h5', format: { eol: '\r\n' } })
    expect(crlf).toContain('\r\n')
    // 所有换行都是 CRLF，没有落单的 \n
    expect(crlf.replaceAll('\r\n', '').includes('\n')).toBe(false)
  })

  it('preserves hand-written #ifndef blocks verbatim', () => {
    // 插件只用正向的平台列表，表达不了"除了某平台都可见"这种写法，
    // 所以 #ifndef 块连同原始注释原样放回、永不改动，和文档承诺的
    // 「手写内容永不修改」一致
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: H5 || MP-WEIXIN',
      '    {',
      '      "path": "pages/index",',
      '      "type": "home"',
      '    },',
      '    // #ifndef MP-ALIPAY',
      '    {',
      '      "path": "pages/other"',
      '    }',
      '    // #endif',
      '  ]',
      '}',
    ].join('\n')

    const merged = mergePagesJson(existing, {
      pages: [{ path: 'pages/index', type: 'home' as const }],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    expect(merged).toContain('// #ifndef MP-ALIPAY')
    expect(merged).toContain('// #endif')
    expect(merged).toContain('pages/other')
    expect(merged.match(/#ifndef/g)).toHaveLength(1)

    // 重跑一遍，原样放回的内容不变
    const rerun = mergePagesJson(merged, {
      pages: [{ path: 'pages/index', type: 'home' as const }],
      subPackages: [],
    }, { platform: 'mp-weixin' })
    expect(rerun).toBe(merged)
  })

  it('collapses a scanned entry into a content-equal #ifndef passthrough', () => {
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
      '    {',
      '      "path": "pages/index",',
      '      "type": "home"',
      '    },',
      '    // #ifndef MP-ALIPAY',
      '    {',
      '      "path": "pages/other"',
      '    }',
      '    // #endif',
      '  ]',
      '}',
    ].join('\n')

    // 扫描在 mp-weixin 上找到了 pages/other：它必须并进 #ifndef
    // 条目（这个条件本来就包含 mp-weixin），而不是多输出一条重复路由
    const merged = mergePagesJson(existing, {
      pages: [
        { path: 'pages/index', type: 'home' as const },
        { path: 'pages/other', type: 'page' as const },
      ],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    expect(merged.match(/"path": "pages\/other"/g)).toHaveLength(1)
    expect(merged).toContain('// #ifndef MP-ALIPAY')
  })

  it('keeps a mid-array #ifndef block closed (stray closer in the next entry)', () => {
    // comment-json 会把收尾的 #endif（它输出在值的逗号后面）挂到
    // 下一个条目的前置注释上。原样放回时仍然必须输出一个闭合的块，
    // 不能让 #ifndef 一直开着——否则在被排除的平台眼里，文件剩下的
    // 部分全被吞掉
    const existing = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
      '    {',
      '      "path": "pages/index",',
      '      "type": "home"',
      '    },',
      '    // #ifndef MP-ALIPAY',
      '    {',
      '      "path": "pages/other"',
      '    },',
      '    // #endif',
      '    {',
      '      "path": "pages/third"',
      '    }',
      '  ]',
      '}',
    ].join('\n')

    const merged = mergePagesJson(existing, {
      pages: [
        { path: 'pages/index', type: 'home' as const },
        { path: 'pages/third', type: 'page' as const },
      ],
      subPackages: [],
    }, { platform: 'mp-weixin' })

    expect(merged.match(/#ifndef/g)).toHaveLength(1)
    expect(merged.match(/#endif/g)).toHaveLength(1)
    expect(merged.indexOf('#ifndef')).toBeLessThan(merged.indexOf('pages/other'))
    expect(merged.indexOf('pages/other')).toBeLessThan(merged.indexOf('#endif'))
    // 搭到下一个条目前置注释里的落单 #endif 会被丢掉，
    // 不会多输出一个
    expect(merged).toContain('pages/third')

    const rerun = mergePagesJson(merged, {
      pages: [
        { path: 'pages/index', type: 'home' as const },
        { path: 'pages/third', type: 'page' as const },
      ],
      subPackages: [],
    }, { platform: 'mp-weixin' })
    expect(rerun).toBe(merged)
  })

  it('does not accumulate generation markers when #ifndef wraps the first entry', () => {
    // 生成标记放在数组最前面（before:0），第一个条目被 #ifndef 包住
    // 时会把它连同 #ifndef 注释一起抓走；如果原样照抄，标记每跑一次
    // 就多一个，永远停不下来
    const seed = [
      '{',
      '  "pages": [',
      '    // GENERATED BY UNI-PAGES, PLATFORM: MP-WEIXIN',
      '    // #ifndef MP-ALIPAY',
      '    {',
      '      "path": "pages/index",',
      '      "type": "home"',
      '    }',
      '    // #endif',
      '  ]',
      '}',
    ].join('\n')

    const data = {
      pages: [{ path: 'pages/index', type: 'home' as const }],
      subPackages: [],
    }
    const once = mergePagesJson(seed, data, { platform: 'mp-weixin' })
    const twice = mergePagesJson(once, data, { platform: 'mp-weixin' })

    expect(once.match(/GENERATED BY UNI-PAGES/g)).toHaveLength(1)
    expect(once).toContain('#ifndef MP-ALIPAY')
    expect(once.match(/#endif/g)).toHaveLength(1)
    expect(twice).toBe(once)
  })

  it('keeps output byte-stable when platforms alternate writing divergent entries', () => {
    // 稳定性回归：合并时当前平台的变体先从自己的 #ifdef 列表里退出
    // 来、又被补到同一键变体列表的末尾。修复前，两个平台轮流运行
    // （dev:h5 和 dev:mp-weixin 轮流写）时，同键变体的顺序每次都
    // 翻转——功能没坏，但文件每次都有一堆无意义的改动。现在变体按
    // 平台列表排序，不管谁先谁后，输出都一样
    const dataFor = (platform: string) => ({
      pages: [platform === 'h5'
        ? { path: 'pages/index/index', type: 'home' as const, style: { navigationBarTitleText: 'h5 首页' } }
        : { path: 'pages/index/index', type: 'home' as const, style: { navigationBarTitleText: 'wx 首页' } }],
      subPackages: [],
    })

    let content = mergePagesJson('', dataFor('h5'), { platform: 'h5' })
    content = mergePagesJson(content, dataFor('mp-weixin'), { platform: 'mp-weixin' })
    const afterFirstRotation = content

    expect(content.match(/#ifdef/g)).toHaveLength(2)
    expect(content.match(/#endif/g)).toHaveLength(2)

    // 任何平台重跑，文件一个字节都不能变；修复前偶数次翻转刚好转回
    // 原样，所以每一步都要比，不能只看最后一步
    for (const platform of ['h5', 'mp-weixin', 'h5', 'mp-weixin', 'h5']) {
      content = mergePagesJson(content, dataFor(platform), { platform })
      expect(content).toBe(afterFirstRotation)
    }
  })

  it('gives every platform its own view across a three-platform rotation', () => {
    // 三个平台轮流跑、样式各不相同、首页也各不相同：每个平台经过
    // 条件编译后看到的条目必须正好是自己的那些（不重复、不缺、
    // 不多），而且首页排在它能看到的非首页条目前面
    const h5Pages = [
      { path: 'pages/index/index', type: 'home' as const, style: { navigationBarTitleText: 'H5 首页' } },
      { path: 'pages/shared/about', type: 'page' as const },
    ]
    const wxPages = [
      { path: 'pages/wx-home/wx-home', type: 'home' as const },
      { path: 'pages/shared/about', type: 'page' as const, style: { navigationBarTitleText: '微信关于' } },
    ]
    const aliPages = [
      { path: 'pages/index/index', type: 'home' as const },
      { path: 'pages/shared/about', type: 'page' as const },
    ]

    const runs: Array<[string, PagesJsonData['pages']]> = [
      ['h5', h5Pages],
      ['mp-weixin', wxPages],
      ['mp-alipay', aliPages],
    ]
    let content = ''
    for (const [platform, pages] of runs) {
      content = mergePagesJson(content, { pages, subPackages: [] }, { platform })
    }

    // 解析条目与其 #ifdef 平台块，模拟 uni-app 条件编译后的视图
    const entries: Array<{ path: string, type?: string, title?: string, ifdef?: string }> = []
    let currentIfdef: string | undefined
    let current: (typeof entries)[number] | undefined
    for (const line of content.split('\n')) {
      const trimmed = line.trim()
      const ifdefMatch = trimmed.match(/^\/\/\s*#ifdef\s+(\S.*)$/)
      if (ifdefMatch) {
        currentIfdef = ifdefMatch[1].trim()
        continue
      }
      if (trimmed === '// #endif') {
        currentIfdef = undefined
        continue
      }
      const pathMatch = trimmed.match(/"path":\s*"([^"]+)"/)
      if (pathMatch) {
        current = { path: pathMatch[1], ifdef: currentIfdef }
        entries.push(current)
        continue
      }
      const typeMatch = trimmed.match(/"type":\s*"([^"]+)"/)
      if (typeMatch && current)
        current.type = typeMatch[1]
      const titleMatch = trimmed.match(/"navigationBarTitleText":\s*"([^"]+)"/)
      if (titleMatch && current)
        current.title = titleMatch[1]
    }
    const viewFor = (platform: string) =>
      entries.filter(e => !e.ifdef || e.ifdef.split('||').map(p => p.trim()).includes(platform))

    const h5View = viewFor('H5')
    expect(h5View.map(e => e.path)).toEqual(['pages/index/index', 'pages/shared/about'])
    expect(h5View[0].title).toBe('H5 首页')
    expect(h5View[0].type).toBe('home')

    const wxView = viewFor('MP-WEIXIN')
    expect(wxView.map(e => e.path)).toEqual(['pages/wx-home/wx-home', 'pages/shared/about'])
    expect(wxView[1].title).toBe('微信关于')
    expect(wxView[0].type).toBe('home')

    const aliView = viewFor('MP-ALIPAY')
    expect(aliView.map(e => e.path)).toEqual(['pages/index/index', 'pages/shared/about'])
    expect(aliView[0].title).toBeUndefined()
    expect(aliView[0].type).toBe('home')

    // 每个视图都没有重复路由；再轮转一周后，各平台重跑都不再改变
    // 文件字节（每一步都比，防止偶数次翻转刚好转回原样、把问题藏住）
    for (const view of [h5View, wxView, aliView]) {
      const paths = view.map(e => e.path)
      expect(new Set(paths).size).toBe(paths.length)
    }
    for (const [platform, pages] of runs) {
      content = mergePagesJson(content, { pages, subPackages: [] }, { platform })
    }
    const rotated = content
    for (const [platform, pages] of runs) {
      content = mergePagesJson(content, { pages, subPackages: [] }, { platform })
      expect(content).toBe(rotated)
    }
  })
})

describe('page metadata merge does not leak style across runs', () => {
  it('keeps cached page style clean when a config override disappears', async () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-merge-leak-'))
    try {
      const pagesDir = path.join(tmpDir, 'src', 'pages', 'index')
      fs.mkdirSync(pagesDir, { recursive: true })
      fs.writeFileSync(
        path.join(pagesDir, 'index.vue'),
        [
          '<script lang="ts" setup>',
          'definePage(() => ({ style: { navigationBarTitleText: \'home\' } }));',
          '</script>',
          '',
          '<template><div>home</div></template>',
          '',
        ].join('\n'),
        'utf-8',
      )

      // 两次运行共用同一个上下文：Page 实例（及其缓存的 meta style
      // 对象）被复用，对这些对象的任何原地改动都会存活到第二次运行
      const ctx = new PageContext({ dir: 'src/pages', dts: false }, tmpDir, 'h5')

      ctx.pagesGlobConfig = {
        pages: [{ path: 'pages/index/index', style: { enablePullDownRefresh: true } }],
      }
      await ctx.scanAndMerge()
      expect(ctx.resolveRoutes()).toContain('enablePullDownRefresh')

      // 覆盖配置消失：生成的条目必须回落到自己的 style，
      // 不残留上一次运行的任何痕迹
      ctx.pagesGlobConfig = {}
      await ctx.scanAndMerge()
      const routes = ctx.resolveRoutes()
      expect(routes).toContain('navigationBarTitleText')
      expect(routes).not.toContain('enablePullDownRefresh')
    }
    finally {
      fs.rmSync(tmpDir, { recursive: true, force: true })
    }
  })
})

describe('writePagesJson change detection reads the disk, not a cache', () => {
  it('rewrites a clobbered pages.json even when the merged output is unchanged', async () => {
    // 变更检测评审问题的回归：过去进程内缓存等于合并结果时会跳过写入，
    // 被外部覆写成 `{}` 的磁盘文件就一直是错的，直到重启
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-changedetect-'))
    try {
      const jsonPath = path.join(tmpDir, 'pages.json')
      const data = {
        pages: [{ path: 'pages/index/index', type: 'home' as const }],
        subPackages: [],
      }
      const options = { platform: 'h5' as const }
      const expected = mergePagesJson('', data, options)

      fs.writeFileSync(jsonPath, '{}', 'utf-8')

      const result = await writePagesJson(jsonPath, data, options)

      expect(result?.updated).toBe(true)
      expect(fs.readFileSync(jsonPath, 'utf-8')).toBe(expected)
    }
    finally {
      fs.rmSync(tmpDir, { recursive: true, force: true })
    }
  })

  it('skips the write when the disk already equals the merged output', async () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-changedetect-'))
    try {
      const jsonPath = path.join(tmpDir, 'pages.json')
      const data = {
        pages: [{ path: 'pages/index/index', type: 'home' as const }],
        subPackages: [],
      }
      const options = { platform: 'h5' as const }
      const expected = mergePagesJson('', data, options)
      fs.writeFileSync(jsonPath, expected, 'utf-8')

      const result = await writePagesJson(jsonPath, data, options)

      expect(result?.updated).toBe(false)
      expect(result?.content).toBe(expected)
    }
    finally {
      fs.rmSync(tmpDir, { recursive: true, force: true })
    }
  })
})
