import type { CommentArray, CommentObject, CommentSymbol } from 'comment-json'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parse as cjParse } from 'comment-json'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { PageContext } from '../packages/core/src'

/**
 * Regression test for https://github.com/uni-helper/vite-plugin-uni-pages/issues/283
 *
 * Symptom: running `dev:h5` then `dev:mp-weixin` (or any two platforms in
 * sequence against the same pages.json) produced duplicate entries for the
 * same page path, breaking the build.
 *
 * Root cause: items coming from `pageMetaData` carry an internal `type`
 * marker (`'home'` / `'page'`), while entries already in pages.json may
 * lack it (legacy output or user edits). `mergePlatformItems` compared the
 * two sides via `JSON.stringify`, so the marker made every cross-platform
 * item look different and a duplicate was appended instead of merged.
 *
 * This test models the exact on-disk sequence (H5 run writes the file first,
 * mp-weixin run reads and merges it) in-process to keep it fast and
 * deterministic. The platform is injected through the PageContext constructor
 * so it does not depend on `process.env.UNI_PLATFORM`.
 */

describe('issue #283: cross-platform run does not duplicate routes', () => {
  let tmpDir: string
  let pagesJsonPath: string

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-283-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages', 'index')
    fs.mkdirSync(pagesDir, { recursive: true })

    // A page whose definePage resolves to identical metadata on every platform,
    // so the only thing that can vary across runs is the platform tag.
    fs.writeFileSync(
      path.join(pagesDir, 'index.vue'),
      [
        '<script lang="ts" setup>',
        'definePage(() => ({ style: { navigationBarTitleText: \'uni-app\' } }));',
        '</script>',
        '',
        '<template><div>home</div></template>',
        '',
      ].join('\n'),
      'utf-8',
    )

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')

    // Seed the file with the legacy shape of an H5 run: a single entry
    // tagged H5 via the GENERATED comment, no `type` marker.
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    {',
        '      "path": "pages/index/index",',
        '      "style": {',
        '        "navigationBarTitleText": "uni-app"',
        '      }',
        '    }',
        '  ],',
        '  "subPackages": []',
        '}',
        '',
      ].join('\n'),
      'utf-8',
    )
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it('keeps a single entry for the same path after a second platform run', async () => {
    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index/index', dts: false, mergePages: true },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()

    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    const parsed = cjParse(content) as CommentObject
    const pages = parsed.pages as CommentArray<CommentObject>
    const samePath = pages.filter(p => p.path === 'pages/index/index')

    expect(samePath).toHaveLength(1)

    // The surviving entry must now cover both platforms, proving the second
    // run merged into the existing one instead of appending a duplicate.
    const generatorComment = (pages[Symbol.for('before:0') as CommentSymbol] as Array<{ value: string }> | undefined)?.[0]?.value ?? ''
    expect(generatorComment).toContain('H5')
    expect(generatorComment).toContain('MP-WEIXIN')
  })
})
