import type { CommentArray, CommentObject, CommentSymbol } from 'comment-json'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parse as cjParse } from 'comment-json'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { PageContext } from '../packages/core/src'

/**
 * https://github.com/uni-helper/vite-plugin-uni-pages/issues/283 的回归测试
 *
 * 症状：先跑 `dev:h5` 再跑 `dev:mp-weixin`（或任意两个平台先后对着
 * 同一份 pages.json 运行）后，同一路径出现重复条目，破坏构建。
 *
 * 根因：来自 `pageMetaData` 的条目携带内部 `type` 标记（`'home'` /
 * `'page'`），而 pages.json 中已有的条目可能没有（遗留输出或用户
 * 编辑）。`mergePlatformItems` 用 `JSON.stringify` 比较两侧，标记让
 * 每个跨平台条目看起来都不同，于是追加了重复条目而非合并。
 *
 * 本测试在进程内模拟磁盘上的真实时序（H5 运行先写文件，mp-weixin
 * 运行读取并合并），保证快速且确定。平台通过 PageContext 构造函数
 * 注入，不依赖 `process.env.UNI_PLATFORM`。
 */

describe('issue #283: cross-platform run does not duplicate routes', () => {
  let tmpDir: string
  let pagesJsonPath: string

  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'uni-pages-283-'))
    const pagesDir = path.join(tmpDir, 'src', 'pages', 'index')
    fs.mkdirSync(pagesDir, { recursive: true })

    // 一个 definePage 在每个平台都算出相同的页面配置，跨运行
    // 唯一可能变化的就是平台标签。
    fs.writeFileSync(
      path.join(pagesDir, 'index.vue'),
      [
        '<script lang="ts" setup>',
        'definePage(() => ({ style: { navigationBarTitleText: \'uni-app\' } }));',
        '</script>',
        '',
        '<template><div>home</div></template>',
        '',
      ].join('\n'),
      'utf-8',
    )

    pagesJsonPath = path.join(tmpDir, 'src', 'pages.json')

    // 以 H5 运行的遗留形态预置文件：单个条目通过 GENERATED 注释标记
    // 为 H5，没有 `type` 标记。
    fs.writeFileSync(
      pagesJsonPath,
      [
        '{',
        '  "pages": [',
        '    // GENERATED BY UNI-PAGES, PLATFORM: H5',
        '    {',
        '      "path": "pages/index/index",',
        '      "style": {',
        '        "navigationBarTitleText": "uni-app"',
        '      }',
        '    }',
        '  ],',
        '  "subPackages": []',
        '}',
        '',
      ].join('\n'),
      'utf-8',
    )
  })

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it('keeps a single entry for the same path after a second platform run', async () => {
    const ctx = new PageContext(
      { dir: 'src/pages', outDir: 'src', homePage: 'pages/index/index', dts: false, mergePages: true },
      tmpDir,
      'mp-weixin',
    )
    await ctx.updatePagesJSON()

    const content = fs.readFileSync(pagesJsonPath, 'utf-8')
    const parsed = cjParse(content) as CommentObject
    const pages = parsed.pages as CommentArray<CommentObject>
    const samePath = pages.filter(p => p.path === 'pages/index/index')

    expect(samePath).toHaveLength(1)

    // 留下的条目必须盖住两个平台，证明第二次运行并进了已有条目，
    // 而不是追加了一条重复的。
    const generatorComment = (pages[Symbol.for('before:0') as CommentSymbol] as Array<{ value: string }> | undefined)?.[0]?.value ?? ''
    expect(generatorComment).toContain('H5')
    expect(generatorComment).toContain('MP-WEIXIN')
  })
})
