import antfu from '@antfu/eslint-config'

export default antfu({
  type: 'lib',
}, {
  // generated by ts-json-schema-generator, whose output has no trailing newline
  ignores: ['packages/schema/schema.json'],
}, {
  files: ['test/**/*.ts'],
  rules: {
    'ts/no-require-imports': 'off',
  },
}, {
  files: ['pnpm-workspace.yaml'],
  rules: {
    'pnpm/yaml-enforce-settings': 'off',
  },
})
