/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index" |
  "/pages/A-top" |
  "/pages/blog/index" |
  "/pages/blog/post" |
  "/pages/define-page/async-function" |
  "/pages/define-page/conditional-compilation" |
  "/pages/define-page/conditional-define" |
  "/pages/define-page/function" |
  "/pages/define-page/nested-function" |
  "/pages/define-page/option-api" |
  "/pages/define-page/platform-injected" |
  "/pages/define-page/remove-console" |
  "/pages/i18n" |
  "/pages/test-json" |
  "/pages/test-jsonc-with-comment" |
  "/pages/test-yaml" |
  "/pages/test" |
  "/pages-sub/about/index" |
  "/pages-sub/about/your" |
  "/pages-sub/index" |
  "/pages/pages-internal-sub/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/define-page/object" | "/pages/tabbar-index-zero" | "/pages/tabbar-no-index" | "/pages/tabbar-list" | "/pages/tabbar-profile"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
