import type { PagesConfig, SubPackages, TabBar } from '@uni-helper/uni-pages-types'
import type { InternalPages } from './types'
import { existsSync } from 'node:fs'
import { writeFile as fsWriteFile, mkdir, readFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { normalizePath } from 'vite'

/** 声明生成需要的路由数据，从合并结果直接取 */
export interface DeclarationInput {
  /** 主包页面配置 */
  pages: InternalPages
  /** 子包页面配置 */
  subPackages: SubPackages
  /** 合并后的 tabBar（配置文件与 definePage 声明的合体） */
  tabBar?: TabBar
  /** 来自 pages.config.ts 的用户配置，tabBar 缺失时的兜底来源 */
  globConfig?: PagesConfig
}

/**
 * 生成 TypeScript 声明文件内容
 * 为 uni-app 的导航 API（navigateTo、redirectTo、switchTab、reLaunch）提供类型提示，
 * 让页面路径在编译期获得类型检查
 *
 * @param input - 合并后的路由数据
 * @returns 声明文件代码字符串
 */
export function getDeclaration(input: DeclarationInput): string {
  const subPagePaths = input.subPackages.map((sub) => {
    return sub.pages.map(v => (`"/${normalizePath(join(sub.root, v.path))}"`))
  }).flat()
  // 用裸路径（不带引号和前导斜杠）参与过滤：page.path 也是裸路径，
  // 直接拿包装后的字符串比较永远不相等，tab 页就从未被排除过。
  // 优先取合并后的 tabBar（配置文件 + definePage 声明的合体），
  // definePage 声明的 tab 页才不会被漏掉
  const tabBarRawPaths = input.tabBar?.list?.map(v => v!.pagePath) ?? input.globConfig?.tabBar?.list?.map(v => v!.pagePath) ?? []
  const tabBarPathSet = new Set(tabBarRawPaths)
  // tab 页只能 switchTab 进入，不应出现在 navigateTo/redirectTo 的
  // url 类型里
  const allPagePaths = [...input.pages.filter(page => !tabBarPathSet.has(page.path)).map(v => `"/${v.path}"`), ...subPagePaths]
  const tabBarPagePaths = tabBarRawPaths.map(p => `"/${p}"`)
  // 一个页面都没有时（全新项目，或所有页面都通过 definePage(null)
  // 退出），没有路径字面量可列：回退成 string，生成的 d.ts 仍然是
  // 合法的 TypeScript，而不是 `type _LocationUrl = ;` 这样的坏代码
  const locationUrlType = allPagePaths.length > 0 ? allPagePaths.join(' |\n  ') : 'string'
  const code = `/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  ${locationUrlType};

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  ${tabBarPagePaths.length ? `url: ${tabBarPagePaths.join(' | ')}` : ''}
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
`
  return code
}

/**
 * 写入文件，自动创建所在目录
 * @param filePath - 文件路径
 * @param content - 文件内容
 */
async function writeFile(filePath: string, content: string): Promise<void> {
  await mkdir(dirname(filePath), { recursive: true })
  return await fsWriteFile(filePath, content, 'utf-8')
}

/**
 * 将声明文件写入磁盘
 * 仅在内容变化时写入，避免不必要的文件操作
 *
 * @param input - 合并后的路由数据
 * @param filepath - 声明文件输出路径
 */
export async function writeDeclaration(input: DeclarationInput, filepath: string): Promise<void> {
  const originalContent = existsSync(filepath) ? await readFile(filepath, 'utf-8') : ''

  const code = getDeclaration(input)
  if (!code)
    return

  if (code !== originalContent)
    await writeFile(filepath, code)
}
